### ISSUE TITLE
Add connman debianization demo

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#103]
We need more real world in-toto examples! This time it's Debian.

The idea is to show how in-toto can be used to guarantee the integrity of a software project from upstream development to installation using a Debian package management tool.

Let's use our great [in-toto Connman OpenSUSE demo](https://github.com/in-toto/in-toto/tree/develop/demo-opensuse) as a basis.

Here are some relevant pointers:

 - Connman [Homepage](https://01.org/connman) and [Upstream Repo](https://git.kernel.org/pub/scm/network/connman/connman.git/)
 - [Debian Developers' Corner](https://www.debian.org/devel/)
 - [Debian Maintainer Guide](https://www.debian.org/doc/manuals/maint-guide/first.en.html)
 - [Debian Connman Package Tracker](https://packages.qa.debian.org/c/connman.html) (with links to package site and git repo)

Additionally, this might be helpful:
 - A Debian Developer's [thoughts on supply chain security](http://madduck.net/blog/2005.08.11:rcs-uploads/)
 - A Debian [hello world package](http://wiki.opf-labs.org/display/SP/The+Hello+World+Debian+Package) and a [packaging diagram](https://danielpocock.com/autotools-project-distribution-and-packaging-on-debian) (*Note: I am not guaranteeing the freshness or relevance of those links*)

**Comment by ShikherVerma** [comment]
@lukpueh grabbing the issue

**Comment by isachit** [comment]
As pointed in [packaging diagram link](https://danielpocock.com/autotools-project-distribution-and-packaging-on-debian), the developer puts the tar ball with all the source code etc. on the web, he could put it on sourceforge or upload it anywhere of his choice. Then, the package maintainers come into picture, he can directly make a git repo by using git-import-orig either from the url of the uploaded tar ball or by downloading the tar ball first into his machine, and then importing it from his file system. He then updates some files, and whenever he thinks the code is ready, he builds the .deb files using git-buildpackage or dpkg-buildpackage. Right? 

Alice is the project owner that creates the root layout. Bob is the developer, and he clones the project's repo and performs some pre-packaging edits. Carl then tests the sources and verifies that its fit to ship. Carl then commits the package which leads to a tag in the packaging repository, with a suffix appended to the upstream version number to indicate which iteration of the package it applies to.

So in our case, bob is the developer who puts the code as a tar ball on sourceforge etc., carl is the package maintainer, and builds the final .deb package. And alice is the owner, who creates the root layout, specifying the functionaries, the actions they perform, and match rules for the steps etc. 

Did I get it right? 

Other relevant link:
[Building debian packages with git buildpackage](http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/man.gbp.import.orig.html)

**Comment by lukpueh** [comment]
This sounds good, Sachit! I think for simplicity we start with the package maintainers and consider upstream as a blackbox (we can later try to use a sublayout for this).

Could you go ahead and list step for step the exact commands a Debian maintainer would use, from retrieving the upstream source code to building the final deb package, plus the files materials/products that are expected for each step? 
Please use the commands described in [Debian's Maintainer reference](https://www.debian.org/doc/manuals/maint-guide/first.en.html). In a subsequent iteration we can decide which inspections make sense to check the byproducts/return value of any testing steps (e.g. lintian).

You can use this thread for your elaborations.

**Comment by isachit** [comment]
Step- Making the directory for the package
Command- ```mkdir <package-name>_<version-number>```

**Comment by isachit** [comment]
step: Make the directory for connman, and retrieve the source code from upstream in it
commands:
``` mkdir connman-src```
```mkdir connman.<version-number>.<sub-version-number>```
``` cd connman-src```
``` curl "https://github.com/isachit/connman/archive/master.zip" -o "connman-src.zip"```
```unzip -a connman-src.zip```
```mv connman-src/* connman.<version-number>.<sub-version-number>```
materials- []
products - a directory containing the connman

step: creating the package skeleton
commands:
``` cd connman.<version-number>.<sub-version-number>```
```dh_make --copyright gpl3 -f ../connman-src/connman-src.zip```
materials-  connman-src.zip 
products- a debian subdirectory, which has all the files needed to build the package
byproducts- 
```connman.<version-number>.<sub-version-number>.orig.zip```
```connman.<version-number>.<sub-version-number>.zip```

step: edit the control file, and fill in the required details
commands:
``` vi debian/control```
materials- control file
products- control file

step: edit the copyright file, changelog file, watch file, rules file(let's call them <type/of/file>)
commands:
``` vi debian/<type/of/file>```
materials- <type/of/file>
products- <type/of/file>

step:building the package
commands:
```dpkg-buildpackage -us -uc```
materials- all the files in the debian directory
products- 
```connman.<version-number>.<sub-version-number>_amd64.changes```
```connman.<version-number>.<sub-version-number>_amd64.deb```
```connman.<version-number>.<sub-version-number>.debian.tar.xz```
```connman.<version-number>.<sub-version-number>.dsc```

**Comment by lukpueh** [comment]
We ended up using `grep` instead of `connman` for the in-toto Debian demo presented at DebConf2017. Here is a list of resources related to the demo:
- [Talk at DebConf2017](https://debconf17.debconf.org/talks/100/) (includes discussion about usability of in-toto in the scope of Debian)
- [Talk Slides](https://annex.debconf.org/debconf-share/debconf17/slides/100_in_toto__securing_supply_chains_as_a_whole.pdf)
- [Demo Screencast and Metadata](https://drive.google.com/drive/folders/0B31TBNxkAWxQaFI3WC0zbExqQU0)
- [Debian Packaging Tutorial](https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf) (the demo is based on this tutorial)
