### ISSUE TITLE
Properly duplicate standard streams

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#11]
Currently we provide a command line flag to `toto-run` to either don't touch stdout and stderr, which is required if `toto-run` wraps interactive commands like e.g. `vi`, or to redirect and store them as byproducts to the link metadata.
Ideally we would like to duplicate the streams to allow both.
- Using a pipe won't work because processes like vi will complain
- Wrapping stdout/sterr in Python won't work because the suprocess will only take the filedescriptor and then uses it natively
- Reading from /dev/(stdout|stderr), /dev/tty is *NIX specific

**Comment by baloyan** [comment]
I have implemented it in C.
Still I am trying to do it in Python, regarding to the Python documentation it is not straightforward (or almost impossible) problem as of today.

**Comment by baloyan** [comment]
OK Lukas, I think I did it in Python. 
The solution is when we have error it write error message in ERROR.log file if we do not have error it means command runs correct so we can write STDOUT in OUT.log file.
Is it OK ?

**Comment by lukpueh** [comment]
The current version of the specification does not mention `stderr` anymore, instead it lists [`stdin` as common byproduct](https://github.com/in-toto/docs/blame/69c29b41f4c1fe064b5d77d61d4b268fc171bcaa/in-toto-spec.md#L912-L917). 

When fixing this issue, let's also investigate how to redirect standard input.
