### ISSUE TITLE
Readme could use a bit more explanation about in-toto workflow

### ISSUE THREAD

**Issue by awwad** [in-toto/in-toto#114]
The [readme](https://github.com/in-toto/in-toto/blob/develop/README.md#in-toto--) explains in-toto's general purpose briefly, then starts explaining what a layout contains, without providing the few sentences that I think would help a reader understand the in-toto workflow.

In particular, I think that the last paragraph of the first section of the readme (*sorry, can't link line numbers in .md in github*) would be better with a little bit more detail. For example, I might change it to something like this:

> ### In-Toto Workflow
> in-toto requires a **project layout** that specifies the functionaries and the tasks they are supposed to perform. The project designer (((or whatever term is preferred))) creates this project layout as a sequence of individual steps, referred to as **links**, designating functionaries to be trusted for each step. The functionaries in charge of each link produce link metadata once they've completed the work in their link, and provide this metadata to (etc.....). The chain of link metadata travels with the final product, and can be validated manually by the final client or via automated tooling in, for example, a package manager.

**Comment by aaaaalbert** [comment]
Re linking to line numbers, @awwad: Does this work for you, https://github.com/in-toto/in-toto/commit/b919735aa44a49a90f295804c1107bedaccff165#diff-04c6e90faac2675aa89e2176d2eec7d8R9 ? (I kept expanding the diff view of the last commit to README.md, then clicked a line number inside of said paragraph.)

**Comment by aaaaalbert** [comment]
Re the proposed edit/sketch, I think these are good pieces of information to add!
