### ISSUE TITLE
Revisit verbosity (stdout/stderr)

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#117]
In https://github.com/in-toto/in-toto/issues/6 we discussed and fixed many initial user feedback issues.
In the course of a layout tool user testing session, it was noted that when looking at stdout/stderr of the used tool (`in-toto-mock`) it was unclear if the command was executed properly or not.

Here are some general user feedback related items open for discussion and fixing:
- Make better use of verbosity levels
- Reduce the output if `-v` flag is not specified
- Make clear if a command failed or not
- Colorize output
- Do something about `subprocess32` warning (seems to confuse users)

**Comment by SantiagoTorres** [comment]
> - Make clear if a command failed or not

imho, this goes against UNIX design principles. I'd suggest to not say anything if the command succeeds.

**Comment by lukpueh** [comment]
I think the *rule of silence* is more flexible than that. What about three verbosity levels? e.g.:
(1) quiet: no output at all
(2) reasonable: a oneliner if the command succeeds, plus warnings and errors
(3) verbose: print everything (our current default)

And we could configure the levels e.g. 
- `(default)`, `-v`, `-vv`, or
- `-q`, `(default)`, `-v`

**Comment by lukpueh** [comment]
Related issue:
The current default verbosity also inundates the unit test output (c.f. @vladimir-v-diaz's [comment](https://github.com/in-toto/in-toto/pull/163#issuecomment-355582253) on an unrelated PR). We should reduce it to a meaningful minimum.

**Comment by lukpueh** [comment]
Related issue:
It would be good to review existing log statements for their appropriateness in content, type (info/warning/debug) and location (c.f. https://github.com/in-toto/in-toto/pull/167#discussion_r160725540).
