### ISSUE TITLE
Adopt order of final product verification routines

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#132]
At some point the specification changed the order of the final product verification routines to only run the inspection commands after having successfully verified all steps' artifact rules.

IIRC, we also talked about only running an inspection command after having verified that inspection's material rules. However, the [current specification](https://github.com/in-toto/docs/blob/69c29b41f4c1fe064b5d77d61d4b268fc171bcaa/in-toto-spec.md#52-verifying-the-final-product) does not indicate that.

Note that this change has implications on the availability of matching targets to a given MATCH rule. So far we were able to match any material or product of any step or inspection, because at the time of rule verification, inspection had been executed and therefore, all link files were available.

Maybe this is something we should discuss/document in https://github.com/in-toto/docs/issues/4?

The relevant code can be found in [`verfylib.in_toto_verify`](https://github.com/in-toto/in-toto/blob/develop/in_toto/verifylib.py#L1162-L1170)

**Comment by SantiagoTorres** [comment]
We should *not* run inspections before checking match rules on all the steps. There are many scenarios to show how this is a bad idea which I should wikify sometime soon. I know this damages the versatility of match rules, but it's a fair tradeoff imho.

As to why we are running all inspections in a batch without verifying the material rules, I'll be added soon. I wanted to keep the diff simple to simplify reviewing. I also wanted to phrase a good rationale on this.
