### ISSUE TITLE
Store matchrules as Matchrule objects and not as lists

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#14]
Currently we store the list representation of `Matchrule` objects in the according `Step` and `Inspection` fields. This is a workaround that allows us to use  `attr`'s convenient `asdict` function when dumping the layout to a file. 

I suggest to [implement our own `asdict` function](https://github.com/hynek/attrs/issues/103#event-825440411) allowing us to store `Matchrules` as objects but returning their list representation instead of  their dict representation when dumping the container layout.

**Comment by lukpueh** [comment]
@JustinCappos prefers to avoid object oriented programming as per [Secure Systems Lab programming recommendations](https://github.com/secure-systems-lab/code-style-guidelines#avoid-objects).

I think *OO* does make sense in some cases, especially for our main entities (`Layout`, `Step`, `Inspection`, `Link`). 
`Matchrules` on the other hand, for which we currently use a not-so-nice workaround anyway, would definitely be a place where we could reduce *OO*.

**Comment by JustinCappos** [comment]
I'd also say that if we feel we have the personnel where an OO design is
going to be better, let's have that discussion.  It's more that in other
projects (Stork vs Seattle), I think we've had a huge win when more novice
programmers contribute to non-OO code.
