### ISSUE TITLE
Revisit command line tool descriptions in README.md

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#159]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
@vladimir-v-diaz mentioned several issues with the README's command line tool descriptions in his gpg support PR review (#150). We should address his comments in a separate PR.

**Current behavior**/**Expected behavior**:
From Vlad's comments:

- Rephrase the general description of `in-toto-run` especially its purpose https://github.com/in-toto/in-toto/pull/150#discussion_r155297699
- Explain what *"passing a command to `in-toto-run`"* means https://github.com/in-toto/in-toto/pull/150#discussion_r155337421
- Reduce emphasis on supported command-line options and add usage examples  instead https://github.com/in-toto/in-toto/pull/150#discussion_r155332638
- Rethink the command hierarchy, e.g. have `in-toto` as single base command with subcommands (`run`, `verify`, `record`, ...), instead of `in-toto-run`, `in-toto-verify`, `in-toto-record`, ... https://github.com/in-toto/in-toto/pull/150#discussion_r155337421
- Add `in-toto-sign` to README (https://github.com/in-toto/in-toto/pull/150#discussion_r155654194)

**Comment by michizhou** [comment]
@lukpueh @alyptik If it's alright with you guys, I would be happy to take up this issue. I would really appreciate it if you guys could provide some supporting docs and reference materials so that I could get started with addressing the comments raised by @vladimir-v-diaz's review in #150. I will open a new PR to address some of the concerns in this issue for review.

**Comment by alyptik** [comment]
@michizhou Great :) It's a tad sparse, but you can find examples and other supporting documentation on the website at [in-toto.github.io](https://in-toto.github.io/metadata-examples.html) or in the [in-toto/docs](https://github.com/in-toto/docs/tree/master/examples) repository. As I suggested in another comment, a possible rewording for #150 would be "executes the **specified** command..." which I feel is a bit clearer.

**Comment by lukpueh** [comment]
@michizhou, yes, great, please go ahead. The best resource is probably the code itself, which should be highly readable and well commented. Please take a look at the [command line tools](https://github.com/in-toto/in-toto/tree/develop/in_toto), they are all named `in_toto_*.py` and the libraries they are calling, that's mostly [`runlib.py`](https://github.com/in-toto/in-toto/blob/develop/in_toto/runlib.py) and [`verifylib.py`](https://github.com/in-toto/in-toto/blob/develop/in_toto/verifylib.py).

And as @alyptik suggested, the in-toto [specification](https://github.com/in-toto/docs/blob/master/in-toto-spec.md) should provide a lot of background information.

**Comment by michizhou** [comment]
@lukpueh Just wanted to let you know that I have updated the README in a way that should address this issue (see PR #234). If there are no other changes that need to be made, I say we close this.

**Comment by lukpueh** [comment]
Thanks @michizhou! I suggest you create a new issue just for the parts that you didn't address in your PR #234, that is command hierarchy (`in-toto <subcommand>`) and we close this one. :)

**Comment by michizhou** [comment]
Not a problem @lukpueh! I just managed to create a new issue (#239) that addresses the concerns about the command hierarchy and addition of more command usage examples. Feel free to start a new discussion over there and finally close this issue. :)

**Comment by lukpueh** [comment]
Addressed with #248
