### ISSUE TITLE
Step and Inspection generalization

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#16]
Steps and Inspection are both items of the software supply supply chain defined in the layout.
Steps are performed by functionaries and correspond to one or more link metadata files, whereas Inspections are performed during toto-verification, which also produces link metadata.
Both item's link metadata is verified against the defined matchrules in a similar fashion. This bears potential for generalization.

I'm inclined to call the generic type `Item` or `LayoutItem`. Any suggestions would be appreciated.

_Note:_
@JustinCappos requested a name change for`toto-run`'s  `--name` flag which sets the name field of a link metadata file and has to correspond to a Step or Inspection name defined in the Layout. He suggested `--step` or `--step-name`. I'd like to keep it abstract for Steps and Inspection, e.g. `--item-name`.

**Comment by JustinCappos** [comment]
Will you run verification using in-toto-run?  I thought this was with
verify...

Justin

**Comment by SantiagoTorres** [comment]
On Tue, Oct 18, 2016 at 08:13:29AM -0700, Justin Cappos wrote:
> Will you run verification using in-toto-run?  I thought this was with
> verify...

Internally, it sounds easier to run inspections using toto-run, and
generate unsigned links (or local links), that can be used to verify
everything. 

I think this will also help with the issue we spoke about yesterday
regarding delegations.

Thanks,
-Santiago.

**Comment by JustinCappos** [comment]
So, how would this look?  Can you post the terminal output, etc. of what I
would see if I were shoulder surfing the functionaries / client?

Justin

**Comment by SantiagoTorres** [comment]
On Tue, Oct 18, 2016 at 08:20:45AM -0700, Justin Cappos wrote:
> So, how would this look?  

I think this is mostly code-wise. Although I'm missing something. To the
user this should be transparent (no mention of using toto-run should
happen on the client side).


> Can you post the terminal output, etc. of what I
> would see if I were shoulder surfing the functionaries / client?

We should do this either way, so let me start preparing something.

Thanks!
-Santiago.

**Comment by JustinCappos** [comment]
Okay, but if seems like the command line argument names are being chosen to
support either a step or a verification.  So, to me, this isn't transparent
to the user.  Maybe the shoulder surfing examples will make us all
converge...

Thanks,
Justin

**Comment by SantiagoTorres** [comment]
On Tue, Oct 18, 2016 at 08:36:33AM -0700, Justin Cappos wrote:
> Okay, but if seems like the command line argument names are being chosen to
> support either a step or a verification.  So, to me, this isn't transparent
> to the user.

Yeah, I see what you mean now. I was thinking merely of code. To me it
would be simpler to have the following:

toto-verify -> runlib -> passes inspection names as arguments to create the link
toto-run -> runlib -> passes the value of --step-name to create the link.

Thanks,
-Santiago.

**Comment by JustinCappos** [comment]
Sure, this makes sense to me.  I was going to suggest this approach.

Also, to revive something you mentioned earlier: I do think the client
should sign the link metadata they generate.

Justin

**Comment by lukpueh** [comment]
re: "Will you run verification using in-toto-run"
It's actually the other way around. We use` in-toto-run` or more precisely, the command wrapper that records link metadata in `runlib`, in verification.

**Comment by lukpueh** [comment]
*re: "I do think the client should sign the link metadata they generate"*

Do you mean the installation/verification client that runs an Inspection (using runlib from withing verifylib)? Because the link metadata produced when running a Step, i.e. `in-toto-run ... -- <step-command>`, already signs the metadata.

**Comment by lukpueh** [comment]
*re:
toto-verify -> runlib -> passes inspection names as arguments to create the link
toto-run -> runlib -> passes the value of --step-name to create the link.*

Yeah this sounds reasonable. In this case we can just call the flag `--step-name`.

Anyway, I still think it would be a good idea to have a general term for Steps and Inspections, if not for `toto-run` then for `verifylib` and cleaner models.

**Comment by JustinCappos** [comment]
Yes, when the client runs an inspection, they would generate and sign link
metadata.

**Comment by lukpueh** [comment]
Hm, I think I don't understand the benefit. Inspection link metadata is created during verification and only kept in memory. Why should we sign it and then verify the signature some function calls later?

**Comment by JustinCappos** [comment]
It's more that one might use it to audit later.  For example, if the end
user Santiago installs gcc, then this becomes part of his supply chain for
PPH.  So, having this metadata is useful for that.

**Comment by lukpueh** [comment]
Okay, I see. By audit you mean an in-toto `in-toto` verification? :) For such thing it would indeed make sense to produce and also persist Inspection link metadata. I can adapt this in the implementation. Do we want to mention it in the specification?

**Comment by JustinCappos** [comment]
I think it should be there.  At least, that makes sense to me.

If a client wants to discard this link metadata, that's fine, but it should
valid to generate it according to the spec.
