### ISSUE TITLE
Metadata pretty print

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#18]
Layout metadata and link metadata is stored in canonical json format. It would be nice to have a way of showing metadata in a logically structured and human friendly way as well.
- order fields logically instead of alphabetically
- strip keys and signatures

**Comment by JustinCappos** [comment]
I'll comment more (after a shoulder surfing example), but I think there are
many subtle things that can be done in the display to make this very clear.

**Comment by lukpueh** [comment]
See #155  for WIP implementation.

**Comment by lukpueh** [comment]
Also see #161 for adding colorizing output.

**Comment by ashutosh887** [comment]
@adityasaky I saw #546
Please let me know if I can work on this

**Comment by lukpueh** [comment]
Thanks, @ashutosh887! @ShubhikaBhardwaj, seems to still be working on it. I suggest you pick a different issue.

**Comment by ashutosh887** [comment]
Sure @lukpueh 
Thanks

**Comment by iferminm** [comment]
Greetings,

Is anyone working on this? I'd like to contribute but there are not so many "good first issue"s. Please let me know

**Comment by ashutosh887** [comment]
Hi @iferminm 

@lukpueh told me that @ShubhikaBharadwaj is still working on this :)
I was planning to

**Comment by lukpueh** [comment]
> Hi @iferminm
> 
> @lukpueh told me that @ShubhikaBharadwaj is still working on this :) I was planning to

This no longer seems to be the case (see https://github.com/in-toto/in-toto/pull/546#issuecomment-1543456450). Feel free to take a stab at it!

**Comment by hojoungjang** [comment]
Hello! I took a stab at this issue on this [PR#631](https://github.com/in-toto/in-toto/pull/631). I would love to see if anyone can review and work together to get this change merged.

**Comment by trishankatdatadog** [comment]
Not that pretty printing isn't nice, but isn't this problem orthogonal to what python-in-toto should do? Aren't there better tools like `jq` that you could use in composition? I say this because I had asked for printing text in colour in securesystemslib which we later regretted because it added unnecessary third-party dependencies just to run python-tuf.

**Comment by hojoungjang** [comment]
Got it, so should I explore using `jq` to achieve similar behavior implemented in my changes and close the PR for now?

**Comment by trishankatdatadog** [comment]
> the

I'd say so. Does anyone else object?

**Comment by adityasaky** [comment]
I think I broadly agree, this may not be something we want to do in the implementation itself.

I wonder about a self contained project that helps represent attestations and layouts. With layouts, we could also visualize them with where artifacts are coming from and the type of steps they represent based on the predicate types they expect (this is very ITE-10/11 based).

**Comment by lukpueh** [comment]
I have to agree with @trishankatdatadog and @adityasaky here. The feature doesn't need to be part of the in-toto code base, but could very well be a stand alone project.

**Comment by tannerjones4075** [comment]
Is this issue still relevant? Or should it be closed?
