### ISSUE TITLE
Support path left strip when recording artifacts

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#194]
**Description of issue or feature request**:
Add support for left stripping artifact paths before storing them to link metadata. This could give more flexibility to functionaries and simplify writing artifact rules.

**Current behavior**:
Artifacts are recorded as full paths or relative to the current working directory from where `in-toto-run` or `in-toto-record` is executed (see [`--materials`/`--products` cli arguments](https://github.com/in-toto/in-toto/blob/develop/in_toto/in_toto_run.py#L39-L46)), e.g:

```
$ in-toto-run --materials /home/foo ../bar baz  <...>
```
```
{
  _type: "link"
  materials : {
    "/home/foo": HASHDICT,
    "../bar": HASHDICT,
    "baz": HASHDICT
  }
  ...
}
```

**Expected behavior**:
```
$ in-toto-run --lstrip-paths /home/  ../ --materials /home/foo ../bar baz  <...>
``` 
```
{
  _type: "link"
  materials : {
    "foo": HASHDICT,
    "bar": HASHDICT,
    "baz": HASHDICT
  }
  ...
}
```

This change could make the (less obvious) `ARTIFACT_BASE_PATH` setting obsolete, which when used makes the artifact recording function change to that path and then look for the artifacts, passed using the `--materials/--products` arguments, relative from that path and also record them as such relative paths. (see [`runlib.record_artifacts_as_dict`](https://github.com/in-toto/in-toto/blob/develop/in_toto/runlib.py#L148-L156))

**Comment by adityasaky** [comment]
I just wanted to put it out there that I'm working on this issue right now.

**Comment by adityasaky** [comment]
Continuing from the related discussion at #249:

We should discuss about adding a `/` at the end of the prefix if it's not already there. I imagine the prefix will always refer to a directory (some ancestor typically). If `/` isn't provided as part of the prefix, the key in the dictionary may then end up beginning as `/foo` instead of just `foo`.

Also, if we choose to add a `/`, that can cause a separate issue if we're not normalizing the prefix and we have a mix of unix and windows-style paths, and a windows-style path ends up with a `/` at the end. Thoughts?

**Comment by lukpueh** [comment]
@adityasaky, I am not so sure about this. Maybe there are cases where the caller wants to end up with `/foo`. I think not adding a trailing prefix would make this option more flexible. You can add a comment  in the code that a trailing separator might be something to consider.

**Comment by adityasaky** [comment]
Okay, sounds good.

**Comment by adityasaky** [comment]
Currently, I've added support for `--lstrip-paths` with a single prefix. What should be the expected behaviour when a user provides multiple prefixes? Handling them iteratively doesn't seem like a good idea, and the other option is to apply every prefix to every path and left strip the longest matching prefix. Is there another option? @SantiagoTorres do you have any thoughts on this?

**Comment by lukpueh** [comment]
I vote for stripping the longest matching prefix and documenting it in the code in and command line help message.

**Comment by SantiagoTorres** [comment]
> I vote for stripping the longest matching prefix and documenting it in the code in and command line help message.

I discussed with @adityasaky yesterday that probably the longest-path prefix may be an issue when multiple prefixes are defined. Take the following example:

```
.
└── foo
    ├── bar
    │   └── baz
    └── baz
```

With `--lprefix foo/bar` and `--lprefix foo`. 

This would essentially yield two files `baz` recorded as having the same path. Needless to say, they may be have different hashes. I'm also unsure as to how the client would handle repeated paths (should we detect this upon verification?). I think by now we would be at the mercy of the ordering/python-dictionary-hash-function.

My proposal is to support multiple -lprefixes but ensure that they are not left-handed substrings of any other (and fail if that's the case).

**Comment by adityasaky** [comment]
As we discussed (today), even that doesn't necessarily solve the problem when two files have the same name and both their paths are left stripped (when one isn't the sub-string of the other). We should check if a key is already in the dict when recording it.

**Comment by lukpueh** [comment]
Since the problem is duplicate keys in the artifact dictionary and not the way how they got there, let's check for those (and fail with a custom exception) instead of restricting the prefixes.

If we find other good reasons for not supporting prefixes that are left-handed substrings of other prefixes, we can of course bar them. Until then, I suggest we proceed with the longest matching prefix plan.

**Comment by SantiagoTorres** [comment]
On Mon, Jan 21, 2019 at 04:23:00PM +0000, lukpueh wrote:
> Since the problem is duplicate keys in the artifact dictionary and not the way how they got there, let's check for those (and fail with a custom exception) instead of restricting the prefixes.
> 
> If we find other good reasons for not supporting prefixes that are left-handed substrings of other prefixes, we can of course bar them. Until then, I suggest we proceed with the longest matching prefix plan.
> 
Why? I still haven't seen a good reason for this, and it feels like it
potentially breaks the principle of least surprise.

**Comment by lukpueh** [comment]
Alright then let's not support them. I'm fine either way.

**Comment by lukpueh** [comment]
Fixed with #250

**Comment by adityasaky** [comment]
I think this can be closed?

**Comment by SantiagoTorres** [comment]
yes, thanks @adityasaky !
