### ISSUE TITLE
PGP subkeys count towards threshold

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto#202]
**Description of issue**:
After @vladimir-v-diaz 's review of [PR](https://github.com/in-toto/in-toto/pull/201#discussion_r174275398) #201, it was found that the threshold check with pgp keys can be bypassed by signing different pieces of link metadata with different subkeys.

**Current behavior**: A malicious functionary is able to bypass threshold verification by signing multiple pieces of link metadata with different subkeys on his private keyring. To do this, all the different subkeys need to be input by the project owner at the time of signing this root layout.

**Expected behavior**: Instead, any subkey and the master key signatures should count as a single signature towards the threshold.

**Comment by yashsriv** [comment]
Hi,

I'm working on this issue. I'll also add a test for this which should fail for current code and pass after my changes.

**Comment by trishankatdatadog** [comment]
Hi guys, any news on this?

**Comment by adityasaky** [comment]
Hi, I'm going to take a stab at this and see if I can help.

**Comment by lukpueh** [comment]
I'll submit a PR later today.
