### ISSUE TITLE
Update docs/comments for exclude patterns

### ISSUE THREAD

**Issue by ofek** [in-toto/in-toto#222]
To reflect https://github.com/in-toto/in-toto/pull/217

**Comment by michizhou** [comment]
@ofek If it's alright with you, I would be happy to finally resolve this issue if it hasn't been taken care of already. I just need to know which documentation files and comments I should update to reflect the exclude patterns addressed in #217. I would greatly appreciate it. Thanks!

**Comment by ofek** [comment]
@michizhou https://github.com/in-toto/in-toto/blob/ac225cd918ce381512f7dfa71cb05b66263f969c/in_toto/runlib.py#L99-L122 maybe more

**Comment by lukpueh** [comment]
IIRC, this is the only place, where we describe exclude patterns in detail, but it doesn't hurt to do a quick grep over the codebase when fixing this issue.

We do have a pointer to above docstring in our [README.md (Available settings)](https://github.com/in-toto/in-toto/#available-settings). Please update accordingly.

**Comment by michizhou** [comment]
@ofek Should I just remove the ["How it differs from .gitignore"](https://github.com/in-toto/in-toto/blob/ac225cd918ce381512f7dfa71cb05b66263f969c/in_toto/runlib.py#L114-L119) part of the docstring then? Or should I also update other parts of the docstring dealing with exclude patterns?

**Comment by lukpueh** [comment]
@michizhou Please read the code and adopt the docstring accordingly.

**Comment by michizhou** [comment]
@lukpueh @ofek Just wanted to let you know that I just created a new PR that should address this issue. Please feel free to take a look over it and let me know if any changes need to be made. Thanks!
