### ISSUE TITLE
Add a helper function to consistently canonicalize file paths instead of handling them individually in each instance

### ISSUE THREAD

**Issue by adityasaky** [in-toto/in-toto#249]
**Description of issue or feature request**: Presently, various different commands spanning several packages are used to canonize a file path depending on context. There are also situations where some operations cannot be performed using standard techniques due to certain edge cases and assumptions.

**Expected behavior**: A helper function to canonize file paths so that no code  must have to deal with it directly. This also ensures any future additions won’t use incorrect implementations.

**Comment by lukpueh** [comment]
Great initiative, @adityasaky!  Can you specify what commands and edge cases you are referring to? I assume you are talking about path normalization in `runlib.record_artifacts_as_dict`?

As far as I can see we use Python's [`os.path.normpath`](https://docs.python.org/3.7/library/os.path.html#os.path.normpath) and we replace Windows-style backward slash file separators with Unix-style forward slashes. FWIW, these were introduced at different times (see c0624605147b85cb1709355a5178a53dbee66f00, 5f2d2032b67e257748402bb8da0c33bbecff0003, fd02124e7aa8cbbec8a217f4df2b4c56562a1a2c) and they are also performed in different places. E.g. `normpath` is done before applying  (git-style) exclude patterns, whereas slashes are replaced afterwards. 

IMHO,  all normalizations should be performed before applying exclude patterns. So that the same (unix-style) patterns work on all platforms.
Same goes for *path prefix stripping* (see #194). I would do all normalization beforehand and then strip the paths. 

Additionally, we could normalize exclude patterns and path prefixes too. But I think that would make it more confusing. Needless to say any behavior should be documented.

What do you think?

**Comment by adityasaky** [comment]
> Can you specify what commands and edge cases you are referring to? I assume you are talking about path normalization in runlib.record_artifacts_as_dict?

Yes, that's where this discussion started. I was talking to @SantiagoTorres about why the project hasn't used `os.path.normcase` instead of replacing `\\` with `/` manually. After all, `os.path.normpath` has been used elsewhere. He explained that there were a few edge cases where the `replace` was a better option. Specifically:
- "the homedir param on the gpg executable respects '/' regardless of it being windows or unix-like"
- also, `normcase` converts the path to lower case, and if another system in the supply chain is not using a case insensitive file system, it could lead to artifacts not matching

I pointed out that someone new to the project could end up using `normcase` without realizing, and that's where the idea to write a helper function to handle all this was born.

And yes, I'm performing the same normalization to prefixes for #194 right now, as the prefixes must match what's in the actual path presented (which have already been normalized at this point).

Does that make sense?

**Comment by lukpueh** [comment]
I don't really understand why you would want to use `normcase`. As the name suggests it normalizes the case in a path (to lower), which we don't require nor desire.
Furthermore, `normcase` converts `/` to `\\` on windows, which we do want before walking the directories, and which we achieve by using `normpath`, but which is the opposite of what we want when storing the paths, where we use `replace`.

Nonetheless, I think it is a good idea to revisit path normalization in `record_artifacts_as_dict`. Regarding prefix stripping I see three ways, of which I prefer the  **2nd**.
1. Don't normalize prefix and strip before normalizing path
    Pro: Probably least ambiguous behavior
    Con: Requires different prefix params on different platforms
2. Don't normalize prefix and strip after normalizing path
    Pro: Same (unix-style) prefix params everywhere; consistent with other (unix-style) params (materials, products, exclude patterns)
    Con: Maybe unexpected behavior on Windows
3. Normalize prefix (and strip after normalizing path)
    Pro: Allows both unix- and windows-style params; maybe less unexpected behavior on windows
    Con: Inconsistent with (unix-style) params in the rest of the user interface, seems more error prone

**Comment by adityasaky** [comment]
Currently, the implementation is the 3rd option. I can switch it to the 2nd. However, rather than unexpected behaviour, won't the `lstrip` just silently fail if it's in unix-style and artifact paths provided are in windows-style?

Separately, we should also discuss about adding a `/` at the end of the prefix if it's not already there. I imagine the prefix will always refer to a directory (some ancestor typically). If `/` isn't provided as part of the prefix, the key in the dictionary may then end up beginning as `/foo` instead of just `foo`.

Also, if we choose to add a `/`, that can cause a separate issue if we're not normalizing the prefix and we have a mix of unix and windows-style paths, and a windows-style path ends up with a `/` at the end. Thoughts?

**Comment by SantiagoTorres** [comment]
> Also, if we choose to add a /, that can cause a separate issue if we're not normalizing the prefix and we have a mix of unix and windows-style paths, and a windows-style path ends up with a / at the end. Thoughts?

To add more context to this, `\` can be both a valid character in an ext4 path *and* a path separator on windows.

**Comment by lukpueh** [comment]
@SantiagoTorres, you are right and this is something we should fix.  The current `replace` calls in https://github.com/in-toto/in-toto/blob/v0.2.3/in_toto/runlib.py blindly replace any backslash in a path.

@adityasaky, when your are working on this issue, can you make sure that we only replace backslashes if `os.path.sep` is one?

**Comment by adityasaky** [comment]
Sure. Either way, we need to confirm what the separator is in Windows. The docs say `\\` but a quick print here on a Windows system gave me `\`. We should explore if `os.name` or `sys.platform` are better bets.

**Comment by lukpueh** [comment]
That's because print only shows the literal backslash (2nd) and not the escape character (1st). You can try the following on your windows machine:
```python
assert(os.path.sep == "\\")  # Should be fine
print(repr(os.path.sep)) # Should print '\\'
```
I wouldn't use `os.name` or `sys.platform`.

**Comment by adityasaky** [comment]
Okay, noted. Thank you!

**Comment by adityasaky** [comment]
I think we can close this one. It hasn't proved to be a problem, and I think the discussion here seems to suggest that the current techniques handle our case well...
