### ISSUE TITLE
Use "{}".format instead of "%s" % ()

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#25]
@SantiagoTorres made a [valid point](https://github.com/in-toto/in-toto/pull/3#discussion_r84121985) in preferring `"{}".format` over  `"%s" % ()` for string formatting.

See more info in the [Python docs](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting):

> Note: The formatting operations described here exhibit a variety of quirks that lead to a number of common errors (such as failing to display tuples and dictionaries correctly). Using the newer str.format() interface helps avoid these errors, and also provides a generally more powerful, flexible and extensible approach to formatting text.

**Comment by vladimir-v-diaz** [comment]
I think the code style guidelines is sprinkled with examples like so:

```Python
print(str(foo) + " wants to get drunk at " + str(bar))
```

**Comment by SantiagoTorres** [comment]
Hmmm, I don't know if `str(foo) + ...` is better memory-wise. I guess for the simple case this wouldn't be a problem.

 Also, it doesn't allow for format specifications such as:
```
 "{:^10}".format(number) # fancily center-align something.
```

**Comment by vladimir-v-diaz** [comment]
I find the examples listed in the guidelines easier to read, however, format() might be more convenient to use.

One could make the case that format() requires more effort to parse since you have to scan the list of variables at the end to make sense of the string, and newcomers would have to look up documentation for special uses of format()

**Comment by JustinCappos** [comment]
What is wrong with using "text "+str(foo)+" more text "+str(bar)  ?

Thanks,
Justin

**Comment by SantiagoTorres** [comment]
> What is wrong with using "text "+str(foo)+" more text "+str(bar) ? 

I think the biggest issue is that + is a binary operator, and thus it can't be smart in the way you concatenate strings. From [here](https://softwareengineering.stackexchange.com/questions/304445/why-is-s-better-than-for-concatenation):

> In Python str is immutable, so the left and right string have to be copied into the new string for every pair of concatenation. If you concatenate four strings of length 10, you will be copying (10+10) + ((10+10)+10) + (((10+10)+10)+10) = 90 characters, instead of just 40 characters. And things gets quadratically worse as the number and size of the string increases. Java optimizes this case some of the times by transforming the series of concatenation to use StringBuilder, but CPython doesn't.

There's also the issue with the lack of format specifiers that I mentioned above.

I don't think this is such a big deal with small strings/examples such as the ones in the coding guidelines though (they are way easier to read overall).

**Comment by JustinCappos** [comment]
Right, I agree that using format strings isn't worth it in most cases.  If
we really need it for something like manipulating large json files, we can
comment this explicitly and explain the code.  So, I would say do not use
format strings except in those cases...

**Comment by SantiagoTorres** [comment]
Agreed. Maybe the best rule of thumb would be:

> use + for short/simple string concatenation unless you require format specifiers (e.g., numeric values). In that case the `.format()` function is preferred over the `%` construction.

Would it be worth adding it somewhere in the coding guidelines?

**Comment by JustinCappos** [comment]
Sure, I think this is a good addition.
