### ISSUE TITLE
Fix summary link naming

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#254]
**Description of issue or feature request**:
As per the [specification](https://github.com/in-toto/docs/blob/master/in-toto-spec.md#451-artifact-rules-in-sublayouts), *"when using sublayouts, the artifact rules that apply to the equivalent step [in the super-layout] are applied to the materials of the first [...] and the products of the last step of the sublayout"*.   To achieve this we [create summary links](https://github.com/in-toto/in-toto/blob/v0.2.3/in_toto/verifylib.py#L1367) for sublayouts to be used for artifact rule verification in the super layout. 

To locate a link during artifact rule verification, we use its corresponding name. E.g. for some step of the super layout, whose artifacts should match the products of a sublayout, pertaining to a step `foo`, a rule could be:  `MATCH * WITH PRODUCTS FROM foo`.

However, currently we assign the [name of the sublayout's first step](https://github.com/in-toto/in-toto/blob/v0.2.3/in_toto/verifylib.py#L1412) to its summary link, which besides posing a problem for match rules, is semantically inaccurate and may lead to namespace collisions (duplicate step names). 

Kudos to @aditya for pointing out that [the summary link naming seemed off](https://github.com/in-toto/in-toto-golang/blob/ba65c84a773271d05c16d1d0a718e98f1bbeeee2/in_toto/verifylib.go#L554-L562). 

**Current behavior**:
- Summary links for sublayouts are assigned the name of its (the sublayout's) first step
- Artifact rule verification for layouts with sublayouts is not tested

**Expected behavior**:
- Summary links for sublayouts should be assigned the name of the corresponding step in the super-layout
- Add tests

**Comment by adityasaky** [comment]
I'm working on a fix for this on the golang repository and can probably apply it here too.

**Comment by adityasaky** [comment]
in-toto/in-toto-golang#19 fixes this issue. I'll apply a similar fix here shortly.

**Comment by adityasaky** [comment]
This can be closed now.
