### ISSUE TITLE
Parametrize writing of inspection links

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#260]
**Description of issue or feature request**:
During final product verification, inspections defined in the layout are *run* in a similar manner as functionaries *run* steps of the layout, generating link metadata (see [`verifylib.run_all_inspections`](https://github.com/in-toto/in-toto/blob/v0.2.3/in_toto/verifylib.py#L160)).

The corresponding link metadata is required for inspection artifact rule verification (see [`verifylib.in_toto_verify#L1551-L1558`](https://github.com/in-toto/in-toto/blob/v0.2.3/in_toto/verifylib.py#L1551-L1558)).

In addition, each link metadata object is written to disk in the `cwd` of where `in_toto_verify` is called (see [`verifylib.run_all_inspections#L211-L214`](https://github.com/in-toto/in-toto/blob/v0.2.3/in_toto/verifylib.py#L211-L214)). This has two reasons:
- propagation of sublayout inspections to the superlayout (see [4.5.3 Inspections on sublayouts](https://github.com/in-toto/docs/blob/master/in-toto-spec.md#453-inspections-on-sublayouts) of the specification).
- auditing

The former reason is only relevant if the inspection links need to be propagated to a superlayout final product for further verification, which is not the case if verification takes place at the end-user.

Also see related discussion in https://github.com/in-toto/in-toto/pull/258.

**Current behavior**:
Link metadata files for inspection's are always written to `cwd` where `in_toto_verify` is called.

**Expected behavior**:
Provide parameter to `in_toto_verify` to control whether link metadata files for inspections should be written to `cwd`.  Several approaches are conceivable:
- a boolean `persist_inspection_links` (only write if True)
- a path string `inspection_link_destination` (only write if supplied)
- a combination of above (only write if boolean is True, write to path if supplied, to cwd otherwise)

**Comment by trishankatdatadog** [comment]
Good idea, but let's not have two parameters, please :)

**Comment by adityasaky** [comment]
Do we want to keep this open for the possibility of supporting passing in a target directory?
