### ISSUE TITLE
Implement legal mechanism to assert authorization for contributions

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#271]
**Description of issue or feature request**:
[CII silver-level best practices](https://bestpractices.coreinfrastructure.org) encourages projects to
> have a legal mechanism where all developers of non-trivial amounts of project software assert that they are legally authorized to make these contributions.  The most common and easily-implemented approach for doing this is by using a [Developer Certificate of Origin (DCO)](https://developercertificate.org/), where users add "signed-off-by" in their commits and the project links to the DCO website.

Furthermore [CII](https://bestpractices.coreinfrastructure.org) recommends DCO
> because it's easy to implement, tracked in the source code, and git directly supports a "signed-off" feature using "commit -s".

TUF also uses a DCO (see their [GVOERNANCE.md](https://github.com/theupdateframework/tuf/blob/develop/docs/GVOERNANCE.md) and [CONTRIBUTORS.rst](https://github.com/theupdateframework/tuf/blob/develop/docs/CONTRIBUTORS.rst) files, they are also using [PROBOT](https://probot.github.io/apps/dco/) to enforce it on PRs).

**Current behavior**:
No such legal mechanism.

**Expected behavior**:
Maybe briefly review available options (CII mentions *Contributor License Agreement*) and implement appropriate legal mechanism.

**Comment by SantiagoTorres** [comment]
I think probot is not a bad idea in this regard. I enabled it for this repository for the time being. Let's see how it works.

**Comment by lukpueh** [comment]
#283 adds DCO info to the contributor docs and governance file and I just updated our cii silver badge. Kudos to @SantiagoTorres for enabling probot!
