### ISSUE TITLE
Link to tag in setup.py's long description field is broken

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#286]
**Description of issue or feature request**:
Since in-toto's `0.2.3.dev2` release the corresponding git tags have `v` as a prefix, e.g. `v0.2.3.dev2`. 

Links to the tags for each version, as shown on in-toto's PyPI pages still uses the old format, and thus 404.

**Current behavior**:
The link in `setup.py`'s `long_description` is `<https://github.com/in-toto/in-toto/tree/{version}>`, which does not exist for versions >= 0.2.3.dev2.

**Expected behavior**:
- Patch link in `long_description` or use tag names without `v`, for future releases
- Create backup tags without `v` for past releases >= 0.2.3.dev2.

**Comment by lukpueh** [comment]
FYI I created lightweight tags, pointing at the `v`-prefixed release tags, to unbreak the links from PyPI.

@SantiagoTorres, any thoughts about how we should do this in the future?

**Comment by lukpueh** [comment]
Independently of a release-tag naming convention, we can start putting our `README.md` into the `long_description` using the new `long_description_content_type` field (see https://github.com/pypa/sampleproject/commit/5be097071c83c935777bde117fa85cd1f64c690a for details).

**Comment by SantiagoTorres** [comment]
wouldn't it be better to update the pypi desc on the next release?

I agree with the later comment though, the description seems lacking.

**Comment by lukpueh** [comment]
>...  update the pypi desc on the next release?

Yep, that's one of the two solutions I suggested above. I'm fine either way.

**Comment by lukpueh** [comment]
@SantiagoTorres, quick question, is there any benefit from `v`-prefixing version numbers in release tags? Is there any standard / best practice?

@koobs from FreeBSD [says](https://github.com/secure-systems-lab/securesystemslib/issues/167#issuecomment-497573001) that they (and other downstream automatic update detectors) look for pure X.Y.Z release tags.

**Comment by koobs** [comment]
@lukpueh More precisely, we cant look for / predict $arbitrarytext prefixed or suffixed. A consistent prefix/suffix is ok, but X.Y.Z is just less cycles to reason about.

**Comment by lukpueh** [comment]
Maybe a consistent release tagging scheme would be something for our [Lab Guidelines](https://github.com/secure-systems-lab/lab-guidelines), which, by the way, might generally benefit from some guidelines/instructions/pointers about releasing software?

What do others think? @SantiagoTorres, @JustinCappos, @awwad, @mnm678?

**Comment by SantiagoTorres** [comment]
Well I don't have any strong preference. I'm all for having a standardized way to do it. I took the v-prefix idea from other projects that I package from arch as it's easier on auto-completion (i.e., `git checkout v[tab]` will generally just autocomplete tags and versions).
