### ISSUE TITLE
Add a test including source and destination prefixes for test_verify_match_rule

### ISSUE THREAD

**Issue by adityasaky** [in-toto/in-toto#315]
Currently, https://github.com/in-toto/in-toto/blob/develop/tests/test_verifylib.py#L405 does not include test cases with `IN` clauses for both source and destination.

**Comment by brandonmichaelhunter** [comment]
I can take a stab at this if no one minds.

**Comment by adityasaky** [comment]
Sure, go for it. Thanks!

**Comment by brandonmichaelhunter** [comment]
Let me know if I got this correct, but it sounds like we need a test case where the IN statement is used for both the source and destination class within a match statement. Is that the correct understanding?

Something like this: MATCH bar IN sub WITH PRODUCTS IN sub FROM dest-item

**Comment by adityasaky** [comment]
That sounds right to me!

**Comment by adityasaky** [comment]
Closed by #456. Thanks @brandonmichaelhunter!

**Comment by brandonmichaelhunter** [comment]
You're welcome and thank you for allowing me to help.
