### ISSUE TITLE
https://www.in-toto.io/ doesn't work

### ISSUE THREAD

**Issue by webknjaz** [in-toto/in-toto#344]
Hi, I've met a link to https://www.in-toto.io/ (with `www.`; here https://rasulkireev.com/writings/pygotham-2019-day-1) and was surprised that it doesn't work.

https://in-toto.io/ works (without `www` subdomain).

I think somebody should configure www to point to the same place and maybe add a redirect if needed.

**Comment by SantiagoTorres** [comment]
Hi @webknjaz, we'll add the redirect soon. Thanks for bringing this to our attention :+1:

**Comment by adityasaky** [comment]
Thanks for bringing this to our attention, @webknjaz. This has now been fixed. :smile:
