### ISSUE TITLE
Errors while running tests on Windows

### ISSUE THREAD

**Issue by IshaVDave** [in-toto/in-toto#365]
I am getting an error for 3 out of 216 tests while running it on a Windows PC. They all belong to the class 'TestRecordArtifactsAsDict' in the 'test_runlib.py' set of tests. They show the same message: 'A required privilege is not held by the client'.

![image](https://user-images.githubusercontent.com/62882240/83274863-f7807980-a1eb-11ea-84bb-d10104ada541.png)

It seems like it is a problem with the symbolic links (symlinks). Although that functionality is said to be supported on Windows on versions starting from Vista, I use Windows 10 and it still throws an error. Maybe it is a different command/ syntax on Windows?

Although I am not familiar with symlinks, I found this article that seemed to be useful while extending the functionality to Windows:
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by adityasaky** [comment]
Interesting, it turns out you need administrative privileges to create symlinks in Windows. Does it still appear if you run your command prompt as administrator (just for testing purposes here, mind)?

**Comment by IshaVDave** [comment]
Yes, that was the first thing I tried. It won't work even if I run the command prompt as an administrator.

**Comment by adityasaky** [comment]
That's quite interesting. Going to defer to one of the windows pros from here. :)

**Comment by SantiagoTorres** [comment]
As of windows 3.8 you need to enable developer mode to be able to symlink from the python interpreter. I wonder if what we want to do in this case is to warn windows users when this happens (i.e., if the tests fail because of no permissions)

**Comment by IshaVDave** [comment]
Okay, I can do that. Should I just update the code via a pull request and then you could approve it and commit the changes?

**Comment by lukpueh** [comment]
@SantiagoTorres, thanks for the hint. A warning makes sense to me.
@IshaDave, can you try running the tests in Python development mode to confirm this? And yes, a pull request would be great. :)

**Comment by IshaVDave** [comment]
I just confirmed it. I get no errors if I run it in developer mode.
