### ISSUE TITLE
duplicate module imports

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto#378]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
@trishankatdatadog was so nice and reported, that we have a few duplicate imports. We should get rid of those, if possible.

https://lgtm.com/projects/g/in-toto/in-toto/?mode=list

**Current behavior**:
duplicate imports, that are not necessary.

**Expected behavior**:
import necessary modules just once.

**Comment by lukpueh** [comment]
FYI *lgtm* has the following [recommendation](https://lgtm.com/projects/g/in-toto/in-toto/?mode=list) to fix this:

*"Remove the from xxx import yyy statement. Add yyy = xxx.yyy if required."*

**Comment by lukpueh** [comment]
(Also, and on an unrelated side-note, in-toto's lgtm report looks pretty good to me.) 💯  

(ping https://github.com/secure-systems-lab/securesystemslib/issues/243)

**Comment by shibumi** [comment]
@lukpueh definitely. It's really nitpicking here. I will quickly prepare a PR for this. I don't think it will take much time.

**Comment by shibumi** [comment]
Fixed in: https://github.com/in-toto/in-toto/pull/379
