### ISSUE TITLE
More test cases for exclude patterns

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto#391]
**Description of issue or feature request**:

We need to make sure, that our exclude implementation satisfies our desired functionality as specified in https://github.com/itsbenwu/in-toto/blob/a51366432a22a2bb1112b10dd07797232c23757d/doc/source/exclude-patterns.md

The exclude patterns specification mentions a few edge cases we are not testing yet:

* A slash followed by two consecutive asterisks and a slash matches path segments between two directories (e.g., a/**/b matches a/b, a/x/b, a/x/y/b and so on).
* A pattern ending with a slash will match all descendant paths. This is equivalent to {pattern}/**. If a pattern matches a directory, all files and subdirectories are also excluded.
* A hash serves as a comment, but it doesn't apply to this context. The hash can be escaped with a back-slash to match a literal hash (i.e., \#).
* An exclamation mark negates the rest of the pattern. Like the hash, this isn't particularly necessary for the context of exclude patterns. This can be escaped with a back-slash to match a literal exclamation mark (i.e., \!).
* A forward slash indicates a directory separator.
* A single / does not match any file.
* Separators at the beginning or middle (or both) of a pattern are relative to the current directory. Separators at the end of the pattern only match directories. (e.g., /frotz matches frotz/ but not doc/frotz, doc/frotz/ matches the doc/frotz/ directory but not a/doc/frotz/; however frotz/ matches frotz/ and a/frotz/).
* To match an absolute path using a pattern, a single forward slash (/) at the beginning of the pattern is not sufficient. A single forward slash is used for relative roots rather than the "actual" root found in absolute paths. Using double forward slashes will get around this (i.e., //<pattern>).
* Leading double asterisks match any preceding path segments (e.g., **/foo matches file or directory foo, and **/foo/bar matches file or directory bar anywhere that is directly under directory foo).

Furthermore we should make sure, that this functionality is operating system independent.

**Current behavior**:

We are not testing all patterns yet.

**Expected behavior**:

We should have at least one test case for each pattern

**Comment by adityasaky** [comment]
Thanks for setting this up, @shibumi!

**Comment by Pa3cia07** [comment]
hello, is this issue still actual?

**Comment by shibumi** [comment]
@Pa3cia07 I think it is. Are you willing to contribute a patch? :D

**Comment by Pa3cia07** [comment]
@shibumi I would like to try it :D

**Comment by shibumi** [comment]
@Pa3cia07  cool. Go ahead. If you have any questions either ping me here, in your PR or in our slack channel on slack.cncf.io

**Comment by adityasaky** [comment]
Closed by @rszamszur in #487.
