### ISSUE TITLE
Change expiration check to match TUF

### ISSUE THREAD

**Issue by joshuagl** [in-toto/in-toto#417]
**Description of issue or feature request**:

There was a discussion in the issue tracker of TUF reference implementation (https://github.com/theupdateframework/tuf/issues/1231) about how expiration datetime's should be compared.

Having done some research into how other security providers are comparing expiration equivalents (i.e. OpenSSL x509 certificate checking code, and GnuPG expiration checks), and how other TUF implementations are performing the same check (rust-tuf, go-tuf), we came to a consensus that the correct way to implement expiration comparisons is:

> expiration <= now

I'm filing this issue because the discussion in the thread suggested it is preferable to have in-toto and TUF specifications and reference implementations behave in the same way on this.

**Current behavior**:

`expires < now`

**Expected behavior**:

`expires <= now`

**Comment by joshuagl** [comment]
It may make sense to hold on updating the reference implementation until a similar change has been made to the specification, see https://github.com/in-toto/docs/issues/42

**Comment by adityasaky** [comment]
The spec change has now been made.

**Comment by MashiatK** [comment]
hi, could i take up the issue?

**Comment by adityasaky** [comment]
Go ahead!

**Comment by ashutosh887** [comment]
@joshuagl @adityasaky Please let me work on this Issue

**Comment by lukpueh** [comment]
Thanks for volunteering, @ashutosh887! We already have a patch for this in: https://github.com/in-toto/in-toto/pull/545.

If you are looking for a good first issue, I recommend: https://github.com/in-toto/in-toto/issues/548

**Comment by adityasaky** [comment]
Closed by #616
