### ISSUE TITLE
Fix MATCH rule ambiguities

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#43]
The current rule type `MATCH` uses the following language:
```
MATCH (MATERIAL|PRODUCT) <path pattern> [AS <target path pattern>] FROM <step name>
```
Currently this reads (my interpretation of the specification):
>`MATERIALS` or `PRODUCTS`, depending on the rule's second element, of a step with `<step name>` and matched by `<target path pattern>`  (if specified) or `<path pattern>` (else), must have a hash that matches the hash of a `MATERIAL` or `PRODUCT`, depending on whether the rule is in the `material_matchrules` or `product_matchrules`, of a step that matches `<path pattern>` and has not been matched by a previous rule. The rule also fails if the target path pattern does not find any artifacts.

When I and @SantiagoTorres, who came up with the language and implemented it, tried to apply these rules in real world software supply chains, we both had difficulties to express what we wanted, which IMHO indicates that the language should be clarified and freed from ambiguities.
The following (or at least most of it) should be unmistakingly clear by just reading the rule:

- **What is the match source and what is the match target?**
   rule in one of step's rule lists VS.  `... FROM <step name>`

- **What is the source artifact type and what is the target artifact type?**
   rule in `material_matchrules` or `product_matchrules`  VS. `MATCH (MATERIAL|PRODUCT)...` 

- **Should there be a target artifact for every source artifact? (currently no)**
  material_matchrule (source): `MATCH PRODUCT *  FROM target-step`
  source materials : `hash(foo) = x`, `hash(bar) = y`
  target products:    `hash(foo) = x`
  Pass?

- **Should there be a source artifact for every target artifact? (currently yes)**
  material_matchrule (source): `MATCH PRODUCT *  FROM target-step`
  source materials : `hash(baz) = x`
  target products:    `hash(baz) = x `, `hash(zap) = y`
  Fail?

- **Should the rule fail if the path pattern does not find any artifacts?**
  `MATCH PRODUCT foo ...` should probably fail if there is no product foo?
  `MATCH PRODUCT * ...` should probably not fail if there is no product?

- **Do we solely match by hash in case of wildcard patterns?**
  material_matchrule (source): `MATCH PRODUCT *  FROM target-step`
  source materials : `hash(new/path/foo) = x`, `hash(bar) = y`
  target products:    `hash(foo) = x`, `hash(baz) = y`
  
- **Can artifacts be matched more than once by different MATCH rules? Would AND, OR operators to concatenate MATCHRULES help here?**

-------

Below is a super explicit language to start the discussion. This might be exaggerated but at the same time still does not express *everything*. I don't say, maximum explicitness is a must, nonetheless implicit behavior should be defined somewhere, e.g. in the specs.

```
MATCH [ALL] (MATERIAL|PRODUCT) <source path pattern> FROM <source step name> WITH [ALL] (MATERIAL|PRODUCT) <target path pattern>  FROM <target step name>
```

**Comment by JustinCappos** [comment]
Okay, I've been thinking about this and I don't have a problem with what
you propose.  I think that philosophically, we may be better off trying
different solutions / grammars / techniques and then seeing what works
well.  I don't know that we have enough expertise at this point to really
know how best to move forward and (as long as we do not mind changing it
later) this seems like a good way to make progress...

**Comment by lukpueh** [comment]
**Re:** *Do we solely match by hash in case of wildcard patterns?*

No! This breaks if we have several files with the same hash in a globbed directory tree (e.g. the often empty `__init__py`).
A solution for this problem would be to use the directory structure in addition to the file hashes, e.g. with the help of hash trees.

The problem that remains is that we can't stop someone from maliciously changing the file names if we ignore them while matching. And if we include the filenames to the hash tree we end up matching by path again, i.e. disallowing intended renames.

As a reminder the reason why we wanted to match just by hash in the first place was that we wanted to allow non-recorded path/name changes between steps.
E.g. product `foo.py` from `Step 1` becomes material `src/foo.py` in `Step 2` and can be matched with `MATCH PRODUCT * AS src/* FROM step1`.

While this example suggests that we could just prepend the non-wildcarded prefix and then check for the actual filename, this won't work with more complex wildcard patterns, e.g. wildcards in filenames or multiple wildcard operators.

**I suggest that we go back to strictly matching the full recorded paths.**

As far as I remember, the main reason why we wanted to allow renames in between steps was that we didn't want to require functionaries to execute every single `mv` command with `in-toto-run` and have a respective entry in the layout.
Now that we allow for multi-part in-toto steps using `in-toto-record` (https://github.com/in-toto/in-toto/pull/52) we don't have this problem anymore.

**Comment by JustinCappos** [comment]
I am okay with this.

In the future, we should perhaps consider wildcards in the cases where it
either is a strict replacement in the source and destination.  So whatever
* was in source, must be the same string in the dest.

If * is in only the source, then this also makes sense to me for situations
where there is a timestamp in a file or directory name.

Anyways, to re-iterate, I am fine with what you propose.  Let's not
complicate this unless we need to.

**Comment by lukpueh** [comment]
It seems that I have accidentally ignored a legitimate scenario where we want to reflect filename/path changes with matchrules. I assumed that the main goal is to guarantee that steps are properly chained together, i.e. products of step `i` are the materials of step `i+1`.

However we also want to provide the possibility to restrict what happens inside of a step. E.g. think of package step that does not modify files but rather restructures the file layout inside of a created archive. We want to be able to have a matchrule, e.g. in a later unpacking inspection that guarantees that the files, now in a different directory, match files from a previous step. 

@SantiagoTorres had a good idea for a grammar that allows us explicit renames, using a subset of [bash's brace expansion](http://wiki.bash-hackers.org/syntax/expansion/brace) in a matchrule's path pattern, i.e.:
```python
 {<source path substring>,<target path substring>}
```


**Example:**
Assume we want to match materials - `base/dev/foo.py`,  `base/dev/bar.py` - from `package` step with the products of `unpackage` step. The files have been moved to `base/dist`. 
```
# Using product_matchrule of unpackage
MATCH MATERIALS base/{dist,dev}/*.py FROM package
```
We apply the pattern `base/dev/*.py` on `package`'s materials and `base/dist/*.py` on `unpackage`'s products and verify that:
```python
hash(base/dev/foo.py) == hash(base/dist/foo.py)
hash(base/dev/bar.py) == hash(base/dist/bar.py)
```


**Restrictions:**
 - Only one replace construct is allowed in a path pattern (mainly for simplicity, we can change this later but we have to keep in mind that this would multiply the possible patterns)
 - No wildcards are allowed inside of the braces (this would undermine our desired explicitness)
 - Commas (`,`) in the replace construct need to be escaped because we use a comma as separator

**Comment by lukpueh** [comment]
We will probably have to restrict the use of wildcards after all. Consider the rule
```MATCH ... *{foo,bar}* ... ``` and a source file `foofoo`. The pattern would map to a target `foobar` as well as to a `barfoo` (no one-to-one mapping).

**Comment by awwad** [comment]
I was pretty confused about this for a while. (It's likely I am still confused about important bits, but perhaps this thought is of use. (: )

It sounds now to me like there are two separate things that you folks are trying to solve using Match Rules:

1. No Tampering Guarantee: Making sure the products of step X are identical to the materials of step X+1. This is always required and fundamental to in-toto, I assume. It seems like there's no complexity to this one: the filenames in the just-received materials should always be exactly the same as the just-produced products, modulo some known root path prefix (current directory?).
2. Constraining Step Owner Behavior: Distrusting owners of a previous step. In some cases (such as if there are things tar'd in a previous step that will be untar'd in this step), there may be expectations about the results of that process and some desire to relate them to components of previous steps.

Those two things should probably not be confused with each other. The second is just one of an infinite space of possible expectations a project owner or step owner might have. If it's common/standard enough for in-toto to optionally handle it for a given step or the project, it should still be a distinguishable process from detection of inter-step tampering.

**Comment by JustinCappos** [comment]
I think that the No Tampering Guarantee you want is orthogonal to this
discussion (or if it isn't, I'm confused).

The constraint of behavior focuses on what one can do within a step.  In
this case, the argument is for having a way to say "this step can move this
thing from foo to bar" (or, more precisely everything from foo/* to
bar/*).  Without this change, I think all we can say is "this step will
delete foo and create bar".

**Comment by lukpueh** [comment]
We do use the same language to provide the no tampering guarantee as well as to constrain what a functionary can do within a step. I agree with @awwad that these are two separate concerns and maybe also could be separated conceptually. 

The first is an in-toto core requirement, whereas the second one is an additional security feature, similar to "constrain stdout/stderr of a step" or "constrain the return value of a step", for which we intended custom inspections.

I can see how the files used in a step are more interesting than stdout/sdterr/return value and why we therefore want core code to provide this ability.

In any case we must agree on what we expect from the matchrules. We need to find a common ground for wildcard's flexibility/convenience, moving/renaming files and still allowing a one-to-one mapping of files.

**Comment by JustinCappos** [comment]
So, what I was responding to is that I'm mildly uncomfortable with having
certain 'step' actions occur between steps.  For example, 'modify' or
'create' likely should not happen between steps because there are no
signatures on the actions.  If you're just doing matching, then of course,
this makes sense to me.  I didn't think hard about what to do with items
moving, but we need to have a decision about whether that should or should
not be possible between steps.

**Comment by SantiagoTorres** [comment]
On Thu, Dec 22, 2016 at 07:54:07AM -0800, Justin Cappos wrote:
> So, what I was responding to is that I'm mildly uncomfortable with having
> certain 'step' actions occur between steps.  For example, 'modify' or
> 'create' likely should not happen between steps because there are no
> signatures on the actions.  If you're just doing matching, then of course,
> this makes sense to me.  I didn't think hard about what to do with items
> moving, but we need to have a decision about whether that should or should
> not be possible between steps.

I understand your concern. This is something what Lukas brought up about
a week ago, but we realized that this can happen during regular
workflows.

One quick example is PPH. Consider the following steps:

1.- Justin writes the code, that will live under pph/*
2.- Santiago, builds the dist tarball. This will create 
    dist/pph-${ver}.tar.gz
3.- Lukas (the end user) runs the inspections, in this case, that the
    files within the tarball are the ones that Justin wrote.

Now, in the case of pph, building the dist tarball will effectively move
pph/* into lib/site-packages/pph/* within the tarball (or something of
the like). This means that we must either

* Provide a way to match these two trees once unpacking is done (i.e., a
  way to say "these two trees are equivalent)

or 

* Provide a way to "prefix" the paths so blindly matching can still be
  done (e.g., a preamble to all the matchrules: PREFIX lib/site-packages/)

In this case, the problem is that the output of the second step, is just
the tarball. However, the file structure was changed while creating the
tarball. Note that this is something that happens in pretty much every
single packager that I checked. 

Now, Lukas and I explored three possibilities to face this specific
problem:

1.- Forget about the packaging inspection, as it may be just a corner
    case that may not be as useful as we think.
2.- Add a new way to record these file changes: somehow figure out a way to
    record the new file structure before packing (maybe do so artificially).
    I believe this is burdensome to users though.
3.- Add a way to match using a more powerful semantic (e.g., bash brace
    expansion, or a prefix preamble), that allows for this filepath changes. 

I think the third option to be the one that may prove itself useful in
case we run into something similar that's not packaging (e.g., path
changes by a configure script). 

So, to wrap things up. Creation and deletion is performed artificially
within the step as part of the operation *in* the step. I understand the
concern of these "invisible" changes, but they seem to appear in common
workflows such as packaging.

I don't know what everyone thinks about the option (3) that we chose.
Maybe I'm too deep into this corner case to notice better paths.

Thanks!
-Santiago.

P.S. Sorry for the radio silence, deadlines for review are today and
I'm still missing a couple of papers.

**Comment by JustinCappos** [comment]
I wonder if I'm getting confused here.

Why doesn't your unpack verification check that the code I wrote in step 1
(my product) is moved to a specific directory in step 3 (the product of a
verification step)?

Thanks,
Justin

**Comment by SantiagoTorres** [comment]
Yup, that's exactly the problem (or one of the solutions, rather).
We need a semantic to say "match this file that used to be here in step
1 to the file that came out of step 3 (which is now in another path).

We could always have two validation steps, one that matches and one that
moves files around, but it feels kuldgeish.

Does this make sense?

Thanks!
-Santiago.

**Comment by JustinCappos** [comment]
Okay, I'm fine with having matching and match-in-alternate-location both be
able to go back across multiple steps.  So to me, this makes sense.

Justin

**Comment by lukpueh** [comment]
Below the summary of our (@SantiagoTorres and I) recent match rule discussions.
We agreed that it is paramount to have a one-to-one mapping between source and target artifacts, by file path and by file hash. Furthermore we want to provide the ability to match across file relocations. These are the properties we need in order to achieve this:

- file path pattern (applied on source and target artifacts)
- prefix source (optional, no wildcards are allowed, will be subtracted from each filtered source artifact path)
- step name source (implicit by the step the rule is appended to)
- artifact type source (material or product, implicit by the list the rule is appended to)
- prefix target (optional, see prefix source)
- step name target (to identify the link that contains the target artifacts)
- artifact type target (to identify the type of target artifacts)

The natural language like rule could look like this:
```
MATCH <pattern> [IN <source prefix>] WITH (MATERIALS | PRODUCTS) [IN <target prefix>] FROM <target step name>
```
Note that the tokens alone are not sufficient, the position also matters.

And here is the algorithm to verify if a match rule passes:
```
Identify source and target material or product sets.
Filter source and target material or product sets using the pattern.
If specified, subtract source prefix from source artifact paths.
If specified, subtract target prefix from target artifact paths.
Assert path and file hash equality of source and target artifact sets.
```

**Comment by JustinCappos** [comment]
I'm fine with this.  The important thing is to make progress and get
experience with this in real scenarios.

**Comment by lukpueh** [comment]
The key findings of the discussion in this thread are reflected in the specs as well as in the recent (merged) PR https://github.com/in-toto/in-toto/pull/70. 

I will close the ticket for now and suggest to re-open in case we see need to rework the artifact rules.
