### ISSUE TITLE
GitHub Actions: Enable windows builds

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#435]
**Description of issue or feature request:**
Configure recently added GitHub Actions workflow (see #432) to run tests on windows too.

**Current behavior:**
tests run on linux and mac

**Expected behavior:**
tests run on linux, mac and windows

Coordinate with https://github.com/secure-systems-lab/securesystemslib/issues/326 and https://github.com/secure-systems-lab/securesystemslib/issues/337.

**Comment by Uttam-Singhh** [comment]
Hello, @lukpueh I would like to work on this can you please guide me!

**Comment by adityasaky** [comment]
Hey @Uttam-Singhh! Let me try and track down some work. I know @SolidifiedRay was working on this and had some failures on Windows. Am I misremembering, Yuanrui? :)

**Comment by SolidifiedRay** [comment]
@adityasaky Yes, there are some test failures on Windows.

**Comment by adityasaky** [comment]
Do you have a branch you could drop here to get @Uttam-Singhh started? :)

**Comment by SolidifiedRay** [comment]
Yes. https://github.com/SolidifiedRay/in-toto/blob/gh-actions-windows/.github/workflows/ci.yml
This file is not very different from the one we are using now. The only difference is that my branch  runs the tests on windows machines and not on Linux or Mac.

**Comment by Uttam-Singhh** [comment]
Am I good to go?

**Comment by adityasaky** [comment]
Yes please, feel free to take a stab at it, while also taking a look at @SolidifiedRay's branch linked above. Thanks!

**Comment by lukpueh** [comment]
I think we can finally close this with https://github.com/in-toto/in-toto/pull/598
