### ISSUE TITLE
Deal with (relative) artifacts path recordings

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#44]
It can occur that the directory in which `toto-run` is executed and the base of the directory to record `materials` and `products` are not the same.
Consider below directory layout and a `toto-run` to be executed in `b` and record materials  in `a`:
```shell
├─/path/to/project
          ├── a
          │   ├── bar
          │   └── foo
          └── b
# in /path/to/project/b
toto-run.py --materials ../a
```
this results in a `materials` list:
```python
materials = [
   "../a/bar" : <hash>
   "../a/foo" : <hash>
]
```
Currently  matchrules would need to add dots or double-dots in the path pattern to match the recorded artifacts. This can be circumvented by using wildcard patterns, which does not seem ideal.

Two possible solutions:
- Ignore leading dots/double dots at verification time
- Add a `base-path` command line option to `toto-run`, record absolute artifact paths, leftstrip base path from absolute artifact path before writing link metadata.

**Comment by JustinCappos** [comment]
I like having a base-path.  Even without "../" being part of this, I can
see how this would be useful...

**Comment by lukpueh** [comment]
@JustinCappos, do you have something specifically useful in mind?
I am also wondering how we should handle the case if recording paths have different base paths, given that one can pass multiple paths to `toto-run`'s record options, e.g.

``` shell
# edge case?
toto-run.py --products /home/lukas/project /var/www/html -- my-local-web-test-deploy-cmd
```

**Comment by JustinCappos** [comment]
I'm not 100% sure I understand.  What do you mean by recording paths?

Does having a 'move' or 'relocate' phrase make sense?

**Comment by lukpueh** [comment]
By "recording paths" I mean paths passed as `--materials` or `--products` arguments to `toto-run.py`. These well be `walked` recursively to record every file, i.e. safe the file path and the file's hash to the materials or products list of a link.
