### ISSUE TITLE
Add support for DSSE

### ISSUE THREAD

**Issue by adityasaky** [in-toto/in-toto#445]
**Description of issue or feature request**:
The new signature wrapper [DSSE](https://github.com/secure-systems-lab/dsse) removes the in-toto's current dependence on canonicalization, and is also open to encodings other than JSON. Moving the signature wrapper definition out of the in-toto specification will also help it focus on its key goals, making it more readable. The switch to the new specification is documented in [ITE-5](https://github.com/in-toto/ITE/pull/13).

**Current behavior**: The reference implementation has no support for DSSE.

**Expected behavior**: The reference implementation must be capable of generating metadata using DSSE as an alternative to the current in-toto document format. In order to do this, the reference implementation must include a DSSE implementation.

**Comment by adityasaky** [comment]
The current document format is shared with our sister project, TUF. The implementation for both projects is provided through [securesystemslib](https://github.com/secure-systems-lab/securesystemslib). The tooling for DSSE implemented can be prototyped here, in in-toto, before deciding how to integrate it with securesystemslib for TUF and other projects to take advantage of.

**Comment by attreyee-muk** [comment]
Hello! I would like to contribute to this project for GSOC'22. Can you please help me to get started with it?

**Comment by adityasaky** [comment]
Hi @a-muk, sure thing!

in-toto is a framework that generates metadata files which can be used to make certain verifiable claims about processes in the software supply chain. This metadata is cryptographically signed and represented using what we call a signature wrapper or envelope. The current signature wrapper is defined in the [in-toto specification](https://github.com/in-toto/docs/blob/master/in-toto-spec.md#42-file-formats-general-principles), with the model defined [here](https://github.com/in-toto/in-toto/blob/develop/in_toto/models/metadata.py#L39) in this implementation. Last year, we decided to retire this signature wrapper in favour of [DSSE](https://github.com/secure-systems-lab/dsse). So, the task detailed here is adding capabilities to this repository to generate in-toto metadata using DSSE as the wrapper rather than `Metablock` I've pointed to above.

Please let me know if you have any more questions. If you'd like to see current in-toto metadata represented using `Metablock`, I recommend playing with the [in-toto demo](https://github.com/in-toto/demo). You can compare their structure with the DSSE specification to see how they differ. Finally, feel free to join #in-toto on the [CNCF slack workspace](https://slack.cncf.io).

**Comment by attreyee-muk** [comment]
Thank you @adityasaky for the overview.

**Comment by PradyumnaKrishna** [comment]
Hello @adityasaky,

I am interested in this project for GSoC'22. I tried to understand the code and according to my understanding, currently `Metablock` handles the operation and need to implement a new model for metadata with DSSE with backward compatibility. Am I correct?

DSSE implementation example was also very clear.
I was reading the ITE-5 when I noticed it says "payload is expected to be a JSON file with a `_type` field" but according to DSSE protocol and envelope `payload` is `<Base64(SERIALIZED_BODY)>`.  I think there might be missing something or I have not understood it correctly.

Also, I love to have some suggestions to prepare for GSoC from you.

**Comment by adityasaky** [comment]
`SERIALIZED_BODY` is of type `bytes` and should be a JSON object which includes a `_type` field. The [protocol](https://github.com/secure-systems-lab/dsse/blob/master/protocol.md#signature-definition) only refers to `SERIALIZED_BODY` for the actual signature calculation while the envelope discusses using base64 encoding since DSSE supports signing arbitrary byte streams that may or may not be directly representable. Does that clarify? :)

**Comment by PradyumnaKrishna** [comment]
Thanks, got it, byte stream cannot be represented in form of JSON thats why envelope encodes it in base64.

There is a [ecdsa.py](https://github.com/secure-systems-lab/dsse/blob/master/implementation/ecdsa.py) in the implementation of DSSE, which I believe provided by `securesystemslib` for in-toto metadata wrapper with DSSE or just have to write similar code when implementing?

**Comment by adityasaky** [comment]
Definitely use `securesystemslib`.

**Comment by chasen-bettinger** [comment]
@adityasaky Is there more work to do here?

**Comment by adityasaky** [comment]
Nope, this should be closed, thanks for the bump.
