### ISSUE TITLE
Expected command pattern instead of strict and relaxed alignment

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#46]
Currently we pass command verification upon strict (must be equal) and relaxed (must have an equal prefix) alignment of recorded command and expected command. The following examples show in what cases the alignment passes or fails.

```python
# Left command is the command recorded by toto-run.py
# Right command is the expected command defined in the layout

# Passes:
["vi", "file1", "file2"] ~ ["vi", "file1", "file2"]

# Passes with warning:
["vi", "file1", "file2"] ~  ["vi"]
["make", "install"] ~  ["make"]

# Fails:
["vi", "file1", "file2"] ~ ["make", "install"]
["/usr/bin/vi", "file1"] ~ []
["vi", "file1", "file2"] ~ ["vi", "file2", "file1"]
["/usr/bin/vi", "file1"] ~ ["vi", "file1"]
```
As one can see in above examples that semantically equal commands sometimes fail whereas syntactically  (relaxed)  equal commands can pass although they have very different semantics.

@vladimir-v-diaz brought up the idea of using match patterns. We could use [regex](https://docs.python.org/2/library/re.html) or a subset of regex like implemented by [fnmatch](https://docs.python.org/2/library/fnmatch.html). This would allow either fail or pass and get rid of the relaxed pass.

In any case command alignment does not provide strong security guarantees, since recorded commands can be easily faked using alias, symlinks or the like.

**Comment by JustinCappos** [comment]
I think that just recording what was run and having the client software
eventually warn (error?) is perhaps the best policy.  Getting too advanced
with this probably isn't worth the time.  So, simply doing a strict check
may be best.  Yes, we know someone could bypass this, but it prevents many
types of accidental 'foot-shooting'...  :)

**Comment by lukpueh** [comment]
Sounds good to me.
