### ISSUE TITLE
Is there an in-toto architecture diagram or model diagram? which storages have been supported?

### ISSUE THREAD

**Issue by liufangwai** [in-toto/in-toto#493]
Is there an in-toto architecture diagram or model diagram? which storages have been supported?

**Comment by adityasaky** [comment]
Hi @liufangwai, I'm unclear what you mean by this. Can you clarify? Do you mean what storage backends this implementation supports for storing metadata?

**Comment by liufangwai** [comment]
> storage

Yes , which storage backend support for storing metadata ?

**Comment by lukpueh** [comment]
in-toto supports reading and writing metadata from and to the local file system. But you can use library functions (e.g. [`in_toto_run`](https://in-toto.readthedocs.io/en/latest/api.html#in_toto.runlib.in_toto_run)) to generate link metadata in memory and write it to any desired storage backend.

**Comment by adityasaky** [comment]
One backend you could consider is [Grafeas](https://github.com/grafeas/grafeas/blob/c188e86dabdab1e99f05772aee40940b1ca6e6e2/proto/v1beta1/intoto.proto).

**Comment by adityasaky** [comment]
Closing now. Please reach out if you have more questions. You can also reach us via the mailing list (in-toto-public@googlegroups.com) or the #in-toto channel on the CNCF Slack workspace (https://slack.cncf.io/).
