### ISSUE TITLE
Create a security policy

### ISSUE THREAD

**Issue by trishankatdatadog** [in-toto/in-toto#506]
**Description of issue or feature request**:

Similar to [go-tuf](https://github.com/theupdateframework/go-tuf/issues/371), we should create a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) so that researchers can properly disclose security issues.

**Comment by lukpueh** [comment]
We have one in https://github.com/in-toto/in-toto#security-issues-and-bugs. But it's a good idea to move it to a canonical place.

**Comment by gracenng** [comment]
Interested in working on this during ContribFest

**Comment by gracenng** [comment]
@lukpueh can you close this issue? I don't have permissions

**Comment by adityasaky** [comment]
Thanks @gracenng!
