### ISSUE TITLE
Accept matchrule string instead of lists

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#51]
I think we should allow the rule to be written as strings. A `.split()` when parsing the rule is not very expensive, whereas a split when writing the rule somehow feels stupid. I for instance script my rules like so:
```python
material_matchrules = ["MATCH PRODUCT yadda yadda".split(), ...]
 ```

**Comment by JustinCappos** [comment]
I don't know about this.  What if there is a space in a file name?

**Comment by lukpueh** [comment]
Good point. I tend to forget that people use spaces in a file name. There is always the possibility of requiring escaping. But that adds some extra complexity. Overall, I don't think this is a pressing issue.

**Comment by lukpueh** [comment]
I think we can close this as won't-change for the reasons pointed out by @JustinCappos and @SantiagoTorres (offline).
