### ISSUE TITLE
allow setting `command` and `byproducts` with `in_toto_record_start` and `in_toto_record_stop`

### ISSUE THREAD

**Issue by idunbarh** [in-toto/in-toto#531]
**Description of issue or feature request**:

We're prototyping using the `in-toto` python package to create layouts and links for [hoppr](https://gitlab.com/hoppr/hoppr).

We're wrapping key steps in the processing with `in_toto.runlib.in_toto_record_start()` and `in_toto.runlib.in_toto_record_stop()`.  The link files look good and validate against the layout, but a lot of the fields are empty.
- `command`
- `byproducts`
- `environment`

When using `in_toto.runlib.in_toto_run()` a terminal command is an argument which is set to the `run` field on the link file. The stdout/stderr is set to the `byproducts`.

There is no method for setting these when using `in_toto.runlib.in_toto_record_start()` and `in_toto.runlib.in_toto_record_stop()`. As of `v1.2.0` this values are set empty. Ideally these would be optional to set when calling in_toto.runlib.in_toto_record_stop.

**Current behavior**:

The current behavior sets these items as empty lists/dicts on `in_toto.runlib.in_toto_record_start()`

- see https://github.com/in-toto/in-toto/blob/6bd25002ef2d930b214288c2d8c0ef3f2a917473/in_toto/runlib.py#L715

**Expected behavior**:

Create default arguments for `in_toto.runlib.in_toto_record_stop()` which would not break the existing functionality, but allow users to pass in `command`, `byproducts`, and `environment` link data.

I'm happy to submit a PR if there is interest.

**Comment by adityasaky** [comment]
This sounds good to me, a PR would be great. Thanks!

**Comment by adityasaky** [comment]
Closed by #564.
