### ISSUE TITLE
Support Signer argument in metadata generation functions

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#532]
**Description of issue or feature request**:
securesystemslib [v0.26.0](https://github.com/secure-systems-lab/securesystemslib/releases/tag/v0.26.0) released an improved signer interface. Supporting [`Signer`](https://github.com/secure-systems-lab/securesystemslib/blob/v0.26.0/securesystemslib/signer/_signer.py#L27) objects as arguments in in-toto metadata generation function allows using arbitrary signing providers (e.g. Google Cloud KMS and Yubikey signers are already available in securesystemslib). Relevant functions are: [`in_toto_run`](https://github.com/in-toto/in-toto/blob/6bd25002ef2d930b214288c2d8c0ef3f2a917473/in_toto/runlib.py#L428), [`in_toto_record_start`](https://github.com/in-toto/in-toto/blob/6bd25002ef2d930b214288c2d8c0ef3f2a917473/in_toto/runlib.py#L603) and [`in_toto_record_stop`](https://github.com/in-toto/in-toto/blob/6bd25002ef2d930b214288c2d8c0ef3f2a917473/in_toto/runlib.py#L745).

IMPORTANT: Coordinate  with https://github.com/in-toto/in-toto/pull/503, which refactors relevant functions to use the new Signer API internally!

**Current behavior**:
Relevant function don't support `Signer` argument.

**Expected behavior**:
Relevant functions  support `Signer` argument.  (`in_toto_record_stop` should also support a [`Key`](https://github.com/secure-systems-lab/securesystemslib/blob/v0.26.0/securesystemslib/signer/_key.py#L17) argument, because unlike existing signing arguments, Signer objects don't necessarily give access to the public key needed for verification.)

**Optional expected behavior**:
Deprecate existing signing arguments in relevant functions (e.g. [`signing_key`](https://github.com/in-toto/in-toto/blob/6bd25002ef2d930b214288c2d8c0ef3f2a917473/in_toto/runlib.py#L459-L460) [`gpg_keyid`, `gpg_use_default`, `gpg_home`](https://github.com/in-toto/in-toto/blob/6bd25002ef2d930b214288c2d8c0ef3f2a917473/in_toto/runlib.py#L459-L460)).

**Comment by chasen-bettinger** [comment]
@lukpueh This ticket ok to pick up?

**Comment by adityasaky** [comment]
I think @ckilcoin may also be working on this.

**Comment by lukpueh** [comment]
> I think @ckilcoin may also be working on this.

@ckilcoin, can you confirm?

**Comment by ckilcoin** [comment]
Yep, currently working on it.

**Comment by lukpueh** [comment]
@ckilcoin, are you still working on this? If not, @chasen-bettinger, are you still interested in taking a stab at it? I'm happy to assist either way. 💪

**Comment by chasen-bettinger** [comment]
@lukpueh I am!
