### ISSUE TITLE
link threshold check is overly complicated

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#548]
This line:

https://github.com/in-toto/in-toto/blob/fbc1eb053dd39c6d1fb307a60bd2c781e667c931/in_toto/verifylib.py#L506-L507

is equivalent to:

```python
valid_authorized_links_cnt = len(set(used_main_keyids))
```

(kudos to X41)

**Comment by ashutosh887** [comment]
@lukpueh Can I work on this?

**Comment by adityasaky** [comment]
Go ahead, @ashutosh887.

**Comment by ashutosh887** [comment]
Only I've to simplify the above code @adityasaky Sir?

**Comment by adityasaky** [comment]
Yep!

**Comment by lukpueh** [comment]
addressed in #573
