### ISSUE TITLE
can not found in-toto-spec.pdf

### ISSUE THREAD

**Issue by shenxianpeng** [in-toto/in-toto#550]
**Description of issue or feature request**:

The specification doc in the following link can not be found on the readme page.

>  ## Specification
> You can read more about how in-toto works by taking a look at the [specification](https://github.com/in-toto/docs/raw/master/in-toto-spec.pdf).

**Current behavior**:

https://github.com/in-toto/docs/raw/master/in-toto-spec.pdf  is not exist

**Expected behavior**:

May be correct link should be https://github.com/in-toto/docs/blob/v0.9/in-toto-spec.pdf

**Comment by adityasaky** [comment]
Fixed in #551, thanks for reporting this!
