### ISSUE TITLE
Bug: `ModuleNotFoundError: No module named 'securesystemslib.process'` when importing `in_toto.runlib`

### ISSUE THREAD

**Issue by idunbarh** [in-toto/in-toto#552]
**Description of issue or feature request**:

It looks like the breaking changes from https://github.com/secure-systems-lab/securesystemslib/pull/505 (removal of `securesystemslib.process`) have not taken be __released__ yet in in-toto. Its fixed in `develop` but not a release yet.

Using
- in-toto==1.3.1
- securesystemslib==0.27.0

**Current behavior**:

```
...
  File "/home/vagrant/.cache/pypoetry/virtualenvs/hoppr-mhU-X0__-py3.10/lib/python3.10/site-packages/in_toto/runlib.py", line 46, in <module>
    import securesystemslib.process
ModuleNotFoundError: No module named 'securesystemslib.process'
```

**Expected behavior**:

Changes to fix `securesystemslib.process` released from `develop`

**Comment by lukpueh** [comment]
Fixed in https://github.com/in-toto/in-toto/releases/tag/v1.3.2
