### ISSUE TITLE
No User ID for Vulnerability Report PGP Key in SECURITY.md

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#566]
*[based on X41 source code audit informational note]*

The SECURITY.md file specifies:

> Optionally, reports that are emailed can be encrypted with PGP. You should use PGP key fingerprint 903B AB73 640E B6D6 5533 EFF3 468F 122C E816 2295.

This PGP key is hard to use because it contains no user ID:
```
$ gpg --recv-keys 903BAB73640EB6D65533EFF3468F122CE8162295
gpg: key 468F122CE8162295: new key but contains no user ID - skipped

$ gpg --encrypt --recipient 903BAB73640EB6D65533EFF3468F122CE8162295
gpg: 903BAB73640EB6D65533EFF3468F122CE8162295: skipped: No public key
gpg: [stdin]: encryption failed: No public key
```

**Solution Advice**
If the key has a user ID, it is recommended to include the public key instead of the fingerprint. This avoids needing a third party to obtain the key as well as avoiding the stripped user ID problem.

If the key has no user ID in its original form, the easiest solution might be to give it a generic name without email address such as "in-toto Security Key".

**Comment by lukpueh** [comment]
I suggest to instead switch to GitHub built-in security reporting feature (see [python-tuf security policy](https://github.com/theupdateframework/python-tuf/security/policy) for inspiration)

**Comment by adityasaky** [comment]
I'm in favour of recommending GitHub's security reporting mechanism _but_ also allowing for encrypted emails as an option for folks not using GitHub.

**Comment by lukpueh** [comment]
I don't have a strong opinion about this, but I'm happy to update #567 and add back the email option. But then we should also fix the issue described here. Any preferences about the recommended solutions? cc @SantiagoTorres
