### ISSUE TITLE
key size argument silently ignored in in-toto-keygen

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#568]
*[based on X41 source code audit informational note]*

When running the in-toto key generation helper, it silently ignores the key size option when creating ECDSA or ED25519 keys. This might lead to confusion regarding the strength of the actual key generated, e.g.:

```bash
in-toto-keygen -t ecdsa -b 120000000 keyfile
```

**Solution Advice**:
X41 recommends to generate a warning message

**Comment by lukpueh** [comment]
Note that adding support for the new securesystemslib signer API will allow using standard/established 3rd-party tools for key creation (see #532, #533).

**Comment by shekhar-chauhan** [comment]
@lukpueh could you please explain the issue, would love to take it up

**Comment by adityasaky** [comment]
@shekhar-chauhan you'll see here (https://github.com/in-toto/in-toto/blob/develop/in_toto/in_toto_keygen.py#L130-L131) that the value of `bits` passed in by the user using the `--bits` flag is only used when generating an RSA key. The user is unaware that if they pass `--bits` when trying to generate an ed25519 or ecdsa key, it has no meaning. I wonder if we just want to log a warning if `--bits` is used with `--type={ecdsa,ed25519}`. I'll defer to @lukpueh on the exact fix (plus on any interplay that has with the signer interface).

**Comment by shekhar-chauhan** [comment]
Say, we would want to add the log. Then will the Log be added, something similar to 
`LOG.error("(in-toto-keygen) {0}: {1}".format(type(e).__name__, e))` ??

Also, once the user input a wrong value, it completely exits. 
Is this fine ? I mean, can we not have something like a while/goto case where he can stay there if he did an honest mistake, and say if he wants to exit, he can just type the magic number/keyword, maybe 'exit' or 'e' or '-1' ?

**Comment by adityasaky** [comment]
> Is this fine ? I mean, can we not have something like a while/goto case where he can stay there if he did an honest mistake, and say if he wants to exit, he can just type the magic number/keyword, maybe 'exit' or 'e' or '-1' ?

Yes, it's preferable to quit entirely and let them re-invoke the command with the right arguments. I'd actually argue that keeping them in a loop would be detrimental if they want to use the `--help` flag to understand where they went wrong, for example.

@lukpueh can we do more than log? Can we use the `--bits` parameter, generalize to say the size of the ECDSA key?

**Comment by shekhar-chauhan** [comment]
@adityasaky how would telling the size of the ECDSA key help in this case? 

Also, can you tell me how may I contribute to this issue?

**Comment by lukpueh** [comment]
Thanks for volunteering, @shekhar-chauhan! Please take a look at the ["Instructions for Contributors" in our Readme](https://github.com/in-toto/in-toto#instructions-for-contributors) and let me know if you need any further help to get started!

Regarding the desired fix, I'm fine with logging as suggested X41. Or we just error out if bits is passed for a non-rsa type. You can take a look at  `in_toto_sign.py`, where we call `parser.print_help` and `parser.error` for wrong invocations of the cli tool.

**Comment by shekhar-chauhan** [comment]
I wrote something:
Could you please check and tell if this what you wanted, I'll go ahead and raise a PR for this then, if you guys are okay with this.
```
  try:
    if args.type == KEY_TYPE_RSA:
      interface._generate_and_write_rsa_keypair( # pylint: disable=protected-access
          filepath=args.name, bits=args.bits, prompt=args.prompt)
    elif args.type == KEY_TYPE_ED25519:
      if args.bits is not None:
        parser.print_help()
        parser.error("wrong arguments: bits specified, ED25519 does not require bits to be provided'")
        sys.exit(1)
      else:
      interface._generate_and_write_ed25519_keypair( # pylint: disable=protected-access
          filepath=args.name, prompt=args.prompt)
    elif args.type == KEY_TYPE_ECDSA:
      if args.bits is not None:
        parser.print_help()
        parser.error("wrong arguments: bits specified, ECDSA does not require bits to be provided'")
        sys.exit(1)
      else:
      interface._generate_and_write_ecdsa_keypair( # pylint: disable=protected-access
          filepath=args.name, prompt=args.prompt)
    else:  # pragma: no cover
      LOG.error(
          "(in-toto-keygen) Unsupported keytype: {0}".format(str(args.type)))
      sys.exit(1)
    sys.exit(0)
```

**Comment by lukpueh** [comment]
Cool, thanks! You can always PR your patches right away. This makes review easier and it will automatically run tests over your code, which will show you some syntax errors. ;) 

Some comments on your design:
- Since the bits arg is only used for rsa keys, I suggest to error out if the key type is not rsa. Then you don't need to write the code twice, and it will even work if we add another key type later. 
- no need to call sys.exit after `parser.error` (see [docs](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.error))
- it's okay to do the check outside of the try block
