### ISSUE TITLE
auto-format code

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#580]
I recently ran black+isort over all of securesystemslib, which used the same custom code style as in-toto, and also started enforcing it in CI: https://github.com/secure-systems-lab/securesystemslib/pull/439.

Let's do the same for in-toto!

Why?
- it makes code authoring and reviewing a lot easier
- the switch can be mostly automated
- there are good remedies to preserve git blame

**Comment by adityasaky** [comment]
This sounds reasonable to me!

**Comment by lukpueh** [comment]
closed by #593
