### ISSUE TITLE
Change two exceptions raised in FileResolver

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#587]
A recent refactor (pr pending) of non-public `record_artifacts_as_dict` revealed non-idiomatic use of exceptions:
https://github.com/in-toto/in-toto/blob/d908a6b8c97786a903932affd626eb15a458b06c/in_toto/resolver/_resolver.py#L71-L72

https://github.com/in-toto/in-toto/blob/d908a6b8c97786a903932affd626eb15a458b06c/in_toto/resolver/_resolver.py#L142-L148

I think we could just fix as suggested inline, without disrupting any users. Because the better suited exceptions ValueError  and OSError (raised by `chdir`) are also documented for the calling public `in_toto_run` function, albeit for other reasons.

Or do other maintainers think this warrants a major release?

**Comment by adityasaky** [comment]
> Or do other maintainers think this warrants a major release?

I think not.
