### ISSUE TITLE
subprocess timeout should be configurable in cli/api

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#603]
**Description of issue or feature request**:
`in-toto-mock`, `in-toto-run`, and `in-toto-verify` CLI tools can run functionary commands (mock, run) or inspections (verify) in a subprocess, whose timeout is hardcoded in the [`settings`](https://in-toto.readthedocs.io/en/latest/settings.html) module. 

Previously, this value was configurable via environment variables and rcfiles, which has been deprecated via https://github.com/in-toto/in-toto/security/advisories/GHSA-wc64-c5rv-32pf.

Now, configuration is only possible when using the API functions for these tools, by monkey-patching the settings module, which is an inconvenient usage pattern.

Instead subprocess timeout should be configurable via command line and function arguments in:
-  [`in-toto-mock`](https://github.com/in-toto/in-toto/blob/0bac5495a295307bebbf3337084869fd04e576fd/in_toto/in_toto_mock.py) /[`runlib.in_toto_mock`](https://github.com/in-toto/in-toto/blob/0bac5495a295307bebbf3337084869fd04e576fd/in_toto/runlib.py#L340)
- [`in-toto-run`](https://github.com/in-toto/in-toto/blob/0bac5495a295307bebbf3337084869fd04e576fd/in_toto/in_toto_run.py) /[`runlib.in_toto_run`](https://github.com/in-toto/in-toto/blob/0bac5495a295307bebbf3337084869fd04e576fd/in_toto/runlib.py#L396)
- [`in-toto-verify`](https://github.com/in-toto/in-toto/blob/0bac5495a295307bebbf3337084869fd04e576fd/in_toto/in_toto_verify.py) / [`verifylib.in_toto_verify`](https://github.com/in-toto/in-toto/blob/0bac5495a295307bebbf3337084869fd04e576fd/in_toto/verifylib.py#L1485)

Support may be added separately for runlib and verifylib.

**Comment by chasen-bettinger** [comment]
@lukpueh Hey, I took a stab at this ticket. Would you review and provide feedback on the technical approach? I also did not understand where `in-toto-mock` and `in-toto-verify` fit into the requirements of this ticket. I didn't see that they were using the timeout. Am I missing something obvious?

**Comment by lukpueh** [comment]
Thanks for helping out with this, @chasen-bettinger. Your PR looks great. We can deal with in-toto-mock and in-toto-run separately.
