### ISSUE TITLE
in-toto 2.0.0 TimeoutExpired issue

### ISSUE THREAD

**Issue by Nikhil52254** [in-toto/in-toto#624]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
(in-toto-run) TimeoutExpired: Command '['make', 'dev_build']' timed out after 9.999981854110956 seconds

**Current behavior**:
Tried added --run_timeout 180 but it does not recognize it and does not execute the cmd issued

**Expected behavior**:

**Comment by Nikhil52254** [comment]
Tried

$ in-toto-run -v -n step_build -k <keyfile> -d in-toto/link-files/ -m <app>/ -p artifacts/container-sha.txt -- make dev_build --run_timeout 180

but the stage build the docker image and neither times out completes without doing anything specified in makefile under dev_build

Can someone help with usage?

**Comment by Nikhil52254** [comment]
@chasen-bettinger can you pls suggest on above

**Comment by adityasaky** [comment]
Thanks for noting this! This feature's been implemented via `--run-timeout` but we haven't cut a release since that was merged. It's also time for a new release so I'm going to cut one later today.

**Comment by Nikhil52254** [comment]
so if i do a pip install intoto will i have the latest from pypi ?

**Comment by adityasaky** [comment]
`pip install in-toto` should give you the latest after I've had a chance to cut a release, this hasn't happened yet. :)

**Comment by adityasaky** [comment]
#625

**Comment by adityasaky** [comment]
https://pypi.org/project/in-toto/2.1.0/

**Comment by Nikhil52254** [comment]
Thanks Aditya. how about the usage
should it be 

$ in-toto-run -v -n step_build -k -d in-toto/link-files/ -m / -p artifacts/container-sha.txt -- make dev_build --run_timeout 180

or 

$ in-toto-run -v -n step_build -k -d in-toto/link-files/ -m / -p artifacts/container-sha.txt -- run_timeout 180 make dev_build

**Comment by Nikhil52254** [comment]
seems to be not merged
installed intoto without specifying any version but it installs 2.0.0 only is it merged to the latest or main ?

$ pip list
Package          Version
---------------- -------
ansible          6.6.0
ansible-core     2.13.6
attrs            23.1.0
awscli           1.25.97
bcrypt           4.0.1
botocore         1.21.49
cffi             1.15.1
colorama         0.4.6
cryptography     41.0.3
docutils         0.19
**in-toto          2.0.0**

**Comment by Nikhil52254** [comment]
I tried installing the new version of in-toto 2.1.0. But still the same error
what am i doing wrong here? I have masked few values as xxxxx for security purpose

Installing collected packages: in-toto
  Attempting uninstall: in-toto
    Found existing installation: in-toto 2.0.0
    Uninstalling in-toto-2.0.0:
      Successfully uninstalled in-toto-2.0.0
**Successfully installed in-toto-2.1.0**
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
$ in-toto-run -v -n step_build -k ~/.docker/trust/private/xxxx.pem -d in-toto/link-files/ -m xxxxxx/ -p artifacts/container-sha.txt -- make dev_build --run_timeout 180
Running 'step_build'...
Recording materials 'xxxxxx/'...
Running command 'make dev_build --run_timeout 180'...
Recording products 'artifacts/container-sha.txt'...
Creating link metadata...
Generating link metadata using Metablock...
Signing link metadata using passed key...
Storing link metadata to 'in-toto/link-files/step_build.xxxxx.link'...
$ ls -ltrh outputs/*
ls: outputs/*: No such file or directory
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1


The first step of dev_build is to mkdir outputs and touch a buildsummary file. Later it does a docker build. None of the steps execute.


If i execute without --run_timeout it timesout after 9.9 seconds.

If i remove docker cmds and just do mkdir and touch directory it works fine without timing out.


Any help on this is much appreciated.

**Comment by adityasaky** [comment]
I can't speak to specifics but you're:
1) using `run_timeout` instead of `run-timeout`, I'm not sure if python's arg parser equates the two
2) passing the timeout override to make rather than to in-toto because it's after the `--` end of options indicator

Generally speaking, please take a look at the docs as well: https://in-toto.readthedocs.io/en/latest/command-line-tools/in-toto-run.html#optional-arguments

**Comment by Nikhil52254** [comment]
Tried the changes but am getting a type error. Kindly suggest.

Please note i have made changes to --run_timeout to --run-timeout as suggested and passing the --run-timeout as the last options argument to in-toto before the "-- command"

P.S: Am using in-toto v2.1.0

$ in-toto-run -v -n step_build -k ~/.docker/trust/private/xxxxxx.pem -d in-toto/link-files/ -m xxxxxx/ -p artifacts/container-sha.txt --run-timeout 20 -- make dev_build
Running 'step_build'...
Recording materials 'xxxxxx/'...
Running command 'make dev_build'...
**(in-toto-run) TypeError: unsupported operand type(s) for +: 'float' and 'str'**
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1
