### ISSUE TITLE
Please add a timeout option to in-toto-verify

### ISSUE THREAD

**Issue by skinny-b** [in-toto/in-toto#694]
**Description of issue or feature request**:
Requesting the option of having `--run-timeout` added to `in-toto-verify`. Within the inspect it makes use of run which has a hardcoded 10 second timeout. Doing something like having `grype` scan a made sbom can timeout
Layout:
```
...
      "inspect": [{
          "name": "sbom_scan",
          "expected_materials": [ ... ],
          "expected_products": [ ... ],
          "run": [
             "grype", "spdx.bom.json", "-f", "low"
          ]
        }
...
```

**Current behavior**:
```
$ in-toto-verify -l ./the.layout --layout-keys ./owner.pub
'-k', '--layout-keys' is deprecated, use '--verification-keys' instead.
(in-toto-verify) TimeoutExpired: Command '['grype', 'spdx.bom.json', '-f', 'low']' timed out after 9.999979632906616 seconds
```

This command updates a database before running a scan so it will take longer than 10 seconds (most of the time)

**Expected behavior**:
Command will run and either pass(return code 0)/fail(return code 1) based upon the inspection result.

**Comment by adityasaky** [comment]
I think adding this is fine. @skinny-b do you want to take a stab at a PR? We already have an arg for in-toto-run that controls this.

**Comment by lukpueh** [comment]
Agreed, this is definitely worth adding.

**Comment by skinny-b** [comment]
I'd like to take a crack at it.

**Comment by lukpueh** [comment]
Added in #695
