### ISSUE TITLE
Add clear contributor docs to canonical location

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#749]
The in-toto Python implementation seems to lack a clear contributor quick start guide. This can be easily fixed:

- create docs/CONTRIBUTING.md, which is the canonical place according to [GitHub Community Standards](https://github.com/in-toto/in-toto/community)
- point to dev installation instructions in https://in-toto.readthedocs.io/en/latest/installing.html#installing-for-development
-  mention the `tox` command and `DCO`
- include in [RTD TOC](https://github.com/in-toto/in-toto/blob/develop/doc/source/index.rst?plain=1#L19)

As a start the whole thing could look very similar to https://theupdateframework.readthedocs.io/en/latest/CONTRIBUTING.html until (excluding) the "Unit Test" section

**Comment by lukpueh** [comment]
other things to add
- running the test suite manually, running individual tests, coverage... (this is similar to instructions for theupdateframework above, except that the test suite aggregation script is called `runtests.py`)
- auto format with black and isort 
  ```
  $ black .
  $ isort .
  ```
- build docs
  ```
  $ cd doc && make html 
  ```

**Comment by DarikshaAnsari** [comment]
@lukpueh I have added contributing.md to docs repo. PTAL !

**Comment by tannerjones4075** [comment]
Should this issue be closed?

**Comment by lukpueh** [comment]
Fixed in #751
