### ISSUE TITLE
Add Contributing Page for New Users in Community Website

### ISSUE THREAD

**Issue by Ayush9026** [in-toto/in-toto#754]
## Description of issue or feature request:
We need to create a separate contributing page for new users on our community website, in line with the [CNCF assessment criteria](https://github.com/cncf/techdocs/blob/main/assessments/criteria.md). This page will include sections for contributing guidelines and instructions for first-time contributors.

Current behavior:
Our website lacks a dedicated contributing page specifically tailored for new users. As a result, new contributors may find it challenging to understand how they can contribute to our community effectively.

Expected behavior:
We expect to have a well-structured contributing page that includes the following sections:

Link to the CONTRIBUTING.md file for detailed contributing guidelines.
Encouragement for new contributors to start with existing "good first issues" to get familiar with the contribution process.
Guidance on reporting any security-related issues through a dedicated channel or contact point.
An example to follow, such as the ["Your First Contribution"](https://github.com/helm/community?tab=readme-ov-file#your-first-contribution) section from the Helm project, to provide a clear path for new contributors.

**Comment by shubhusion** [comment]
@Ayush9026 Kindly Assign this issue to me

**Comment by Ayush9026** [comment]
Hello @shubhusion , I'm also actively working on this issue. However, if for any reason I'm unable to work on it, please feel free to go ahead and solve it. Additionally, you're welcome to tackle other issues as well. Let's collaborate to make progress on improving our community website!

**Comment by shubhusion** [comment]
@Ayush9026 u r working on it ?
