### ISSUE TITLE
 Establish workflow for Python Reference Doc edits

### ISSUE THREAD

**Issue by jbogarthyde** [in-toto/in-toto#755]
*UPDATE 05/27/2024 (transfer issue from in-toto/docs)*

 -  [ ] Fix *Edit the Doc* button. 
      The generated reference documentation for the  Python Reference Implementation includes an *Edit the Doc* button. Currently, the button points directly to the source files.  Change the button action to point to the [contribution policy](https://github.com/in-toto/community/blob/main/CONTRIBUTING.md). 
 -  [ ] Provide instructions for editors.  
      Update [contribution policy](https://github.com/in-toto/community/blob/main/CONTRIBUTING.md) to add specific information about where the source code is found and who can review and approve changes to reference docs.

**Comment by lukpueh** [comment]
This issue seems specific to the Python in-toto implementation. I'll transfer the issue to that repo.

**Comment by lukpueh** [comment]
> [contribution policy](https://github.com/in-toto/community/blob/main/CONTRIBUTING.md).


IMO this shouldn't point to project-wide contribution docs, but rather to in-toto/in-toto -specific contribution docs: https://github.com/in-toto/in-toto/blob/develop/doc/source/CONTRIBUTING.md#build-documentation

**Comment by tannerjones4075** [comment]
Should this be closed as it is merged in the https://github.com/in-toto/community/pull/32https://github.com/in-toto/community/pull/32?

**Comment by lukpueh** [comment]
> Should this be closed as it is merged in the [in-toto/community#32](https://github.com/in-toto/community/pull/32)?

No: https://github.com/in-toto/community/pull/32#issuecomment-2175612723

**Comment by DarikshaAnsari** [comment]
@lukpueh Since I have already added the instruction for editors, I just need to change the button to point to https://github.com/in-toto/in-toto/blob/develop/doc/source/CONTRIBUTING.md#build-documentation in this issue.

**Comment by DarikshaAnsari** [comment]
Can you also specify exactly which button this issue is pointing towards? Is it the button(Edit on Github) on the right-hand side of the page?
![image](https://github.com/in-toto/in-toto/assets/100822529/c84df7c9-4b30-47f7-b047-252f913340c8)

**Comment by lukpueh** [comment]
> @lukpueh Since I have already added the instruction for editors, I just need to change the button to point to https://github.com/in-toto/in-toto/blob/develop/doc/source/CONTRIBUTING.md#build-documentation in this issue.

I think that's fine, unless you can think of anything else that would be helpful to someone who wanted to make a docs contribution. E.g. we could mention the tech stack we use for docs ([napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/), [sphinx](https://www.sphinx-doc.org/en/master/), [readthedocs](https://about.readthedocs.com)) and where docs source live...

**Comment by lukpueh** [comment]
> Can you also specify exactly which button this issue is pointing towards? Is it the button(Edit on Github) on the right-hand side of the page?

I think it is.

**Comment by DarikshaAnsari** [comment]
@lukpueh I think this issue is solved please close this one , or let me know if there is anything left i can work on.
