### ISSUE TITLE
Coalesce signature verification in-toto verify

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto#82]
As it is now, there are two places that perform signature verification. Following review #77, we decided that both routines could be placed in the same place, and have the second place just verify that the signature matches the keyid prefix in the filename.

**Comment by lukpueh** [comment]
This actually happened in https://github.com/in-toto/in-toto/pull/85. However, the way we verify signatures is somewhat confusing. I'll close here and will open a new "revisit signature verification" ticket.
