### ISSUE TITLE
Clean up unit-test code.

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto#87]
Some of the unit test code needs to be refactored and cleaned up.

This issue is left up ambiguous intentionally, as it will be discussed in an upcoming hackathon.

**Comment by lukpueh** [comment]
From a note in a23e3570374339433af04dd168b5b06feff9f2ba:
>[the test keys'] keyids, as they appear e.g. in the link filenames [write-code.c8650e01.link and package.2dc02526.link] and in "demo.layout.template", are actually outdated. I.e. if these keys ("bob" and "carl") are imported from PEM format into securesystemlib's rsa key format and hashed to generate the keyid, that keyid would be different.
The reason is that securesystemlib's key format has changed to to include a field "keyid_hash_algorithms" when creating the hash/keyid.

This should be taken care of when fixing this issue

**Comment by gvjkumar2004** [comment]
I would like to work on this issue !

**Comment by adityasaky** [comment]
Go ahead!

**Comment by ashutosh887** [comment]
@adityasaky Let me work on this now

**Comment by Ayush9026** [comment]
@adityasaky sir i want to solve this issue.

**Comment by lukpueh** [comment]
> @adityasaky sir i want to solve this issue.

Thanks, @Ayush9026, contributions are very much appreciated! Do you have any specific refactorings in mind? From what I see this issue requires some discussion about the scope first.

**Comment by tannerjones4075** [comment]
Is this issue still relevant or should it be closed?

**Comment by lukpueh** [comment]
The scope of this issue is quite unclear and probably too broad. Let's close and resubmit, if we have something more specific in mind.
