### ISSUE TITLE
Add `in-toto-keygen` utility

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto#96]
Currently in-toto provides some [utility functions](https://github.com/in-toto/in-toto/blob/develop/in_toto/util.py) to create (password encrypted) RSA key pairs programatically.

It would be nice to additionally have a command line utility, e.g. `in-toto-keygen`, for key creation (like a stripped down `ssh-keygen`).

Keep in mind that we might want to [drop the util module](https://github.com/in-toto/in-toto/issues/80) at some point and move its (updated) functionality to [securesystemslib/keys](https://github.com/secure-systems-lab/securesystemslib/blob/master/securesystemslib/keys.py).

**Comment by isachit** [comment]
On it.

**Comment by lukpueh** [comment]
Implemented with https://github.com/in-toto/in-toto/pull/102
